import { TrainingTrack } from '@/types/courses';

export const TRAINING_TRACKS: TrainingTrack[] = [
  {
    id: 'sap-b1-logistics',
    code: 'SAP-B1-LOGISTICS',
    title: 'SAP Business One: Núcleo Transversal & Finanzas NIIF',
    shortTitle: 'SAP B1 Core & Finanzas',
    category: 'ERP Core',
    iconName: 'Server',
    badge: 'Estándar SAP B1',
    description: 'Estructura transaccional y financiera completa de SAP Business One: Plan de Cuentas NIIF, ciclos Order-to-Cash, Procure-to-Pay, Inventario multialmacén y MRP.',
    targetAudience: 'Analistas Contables, Jefes de Compras/Ventas, Administradores ERP y Consultores de Implementación.',
    totalDurationHours: 65,
    submodulesCount: 8,
    submodules: [
      {
        id: 'b1-01',
        code: 'DOC-SAP-001',
        title: 'Administración: Configuración Maestra y DTW',
        level: 'ARQ',
        durationHours: 8,
        description: 'Inicialización de la compañía, ejercicio fiscal, procedimientos de aprobación y migración masiva con Data Transfer Workbench.',
        keyTopics: ['Definición de sociedades', 'Series de numeración', 'Flujos de aprobación por montos', 'DTW templates'],
      },
      {
        id: 'b1-02',
        code: 'DOC-SAP-003',
        title: 'Finanzas NIIF y Determinación de Cuentas (G/L)',
        level: 'ARQ',
        durationHours: 10,
        description: 'Mapeo de cuentas contables por almacén, grupo de artículos y reglas de contabilización automática en transacciones.',
        keyTopics: ['Plan de cuentas NIIF', 'Cuentas puente de nómina', 'Asientos recurrentes', 'Determinación de mayor'],
      },
      {
        id: 'b1-03',
        code: 'DOC-SAP-002',
        title: 'Gestión Maestra: Socios de Negocios (OCRD) y Artículos (OITM)',
        level: 'OP',
        durationHours: 6,
        description: 'Alta y mantenimiento integral de clientes, proveedores, listas de precios y matrices de descuento.',
        keyTopics: ['Ficha OCRD', 'Condiciones de pago', 'Maestro OITM', 'Catálogo de artículos'],
      },
      {
        id: 'b1-04',
        code: 'DOC-SAP-010',
        title: 'Ciclo Order-to-Cash: De la Oportunidad a la Factura A/R',
        level: 'OP',
        durationHours: 8,
        description: 'Flujo de ventas integral con verificación de disponibilidad ATP, entregas y emisión de factura.',
        keyTopics: ['Cotización y pedido', 'Packing list y picking', 'Factura A/R', 'Gestión de cartera'],
      },
      {
        id: 'b1-05',
        code: 'DOC-SAP-012',
        title: 'Ciclo Procure-to-Pay: De la Requisición al Pago A/P',
        level: 'OP',
        durationHours: 8,
        description: 'Aprovisionamiento corporativo, órdenes de compra, entradas de mercancía (GRPO) y conciliación con factura de proveedor.',
        keyTopics: ['Solicitud de compra', 'Orden de compra (OC)', 'GRPO', 'Factura A/P y retenciones'],
      },
      {
        id: 'b1-06',
        code: 'DOC-SAP-015',
        title: 'Inventario Avanzado: Métodos de Valoración y Lotes',
        level: 'ARQ',
        durationHours: 9,
        description: 'Configuración de FIFO, Promedio Ponderado Móvil y Estándar. Trazabilidad de lotes y números de serie.',
        keyTopics: ['FIFO vs Promedio Ponderado', 'Control de vencimientos', 'Conteo cíclico', 'Ubicaciones (bins)'],
      },
      {
        id: 'b1-07',
        code: 'DOC-SAP-020',
        title: 'Producción y Planificación de Requerimientos (MRP)',
        level: 'ARQ',
        durationHours: 9,
        description: 'Listas de materiales (BOM), órdenes de producción, reporte de piso con backflush y corridas de MRP.',
        keyTopics: ['Listas de materiales BOM', 'Mano de obra y maquinaria', 'Escenarios MRP', 'Costeo de producción'],
      },
      {
        id: 'b1-08',
        code: 'DOC-SAP-016',
        title: 'Informes, Query Generator y Cockpit SAP HANA',
        level: 'OP',
        durationHours: 7,
        description: 'Consultas avanzadas en SQL/HANA, diseño en Crystal Reports y visualización en dashboards analíticos interactivos.',
        keyTopics: ['Generador de consultas SQL', 'Crystal Reports', 'KPIs en Cockpit', 'Dashboards ejecutivos'],
      },
    ],
  },
  {
    id: 'sap-loc-ec',
    code: 'SAP-LOC-EC',
    title: 'Localización Ecuador: Facturación Electrónica & SRI Compliance',
    shortTitle: 'Localización Ecuador SRI',
    category: 'Tributación & Compliance',
    iconName: 'ShieldCheck',
    badge: 'SRI Ecuador 2026',
    description: 'Ingeniería de parametrización tributaria en SAP Business One: emisión de comprobantes XML autorizados por el SRI, retenciones en la fuente (códigos 312, 343, 332, 344), generación del ATS y metadatos con UDFs.',
    targetAudience: 'Contadores Generales, Analistas de Impuestos, Auditores Fiscales y Consultores Funcionales SAP.',
    totalDurationHours: 48,
    submodulesCount: 6,
    submodules: [
      {
        id: 'loc-01',
        code: 'DOC-LOC-011',
        title: 'Facturación Electrónica SRI: Transmisión XML y Firma Digital',
        level: 'OP',
        durationHours: 8,
        description: 'Emisión de facturas, notas de crédito, notas de débito y guías de remisión con firma electrónica y web services del SRI.',
        keyTopics: ['Esquemas XSD SRI', 'Clave de acceso de 49 dígitos', 'Ambiente pruebas/producción', 'RIDE en PDF'],
      },
      {
        id: 'loc-02',
        code: 'DOC-LOC-008',
        title: 'Retenciones en la Fuente: Parametrización Códigos SRI',
        level: 'ARQ',
        durationHours: 10,
        description: 'Mapeo maestro de códigos tributarios: 312 (bienes 1.75%), 343 (construcción 1%), 332 (honorarios 8%) y 344 (servicios 2.75%).',
        keyTopics: ['Tablas de retención', 'Cuentas de pasivo tributario', 'IVA presuntivo y retención', 'Fechas de vigencia'],
      },
      {
        id: 'loc-03',
        code: 'DOC-LOC-009',
        title: 'Ingeniería de Metadatos: UDFs y UDTs para el Cumplimiento Fiscal',
        level: 'ARQ',
        durationHours: 8,
        description: 'Inyección de campos de usuario en tablas nativas: U_TipoIdentificacion en OCRD, U_SustentoTributario y U_FormaPagoSRI en OPCH.',
        keyTopics: ['Herramientas de personalización SAP', 'UDFs en OCRD/OPCH', 'Validación de RUC/Cédula', 'Sustento tributario'],
      },
      {
        id: 'loc-04',
        code: 'DOC-LOC-013',
        title: 'Anexo Transaccional Simplificado (ATS): Generación y Cuadre',
        level: 'OP',
        durationHours: 8,
        description: 'Proceso de extracción de transacciones, validación del archivo XML y conciliación contra los libros de compras y ventas.',
        keyTopics: ['Estructura XML del ATS', 'Cuadre con Formularios 104 y 103', 'Corrección de inconsistencias', 'Plazos SRI'],
      },
      {
        id: 'loc-05',
        code: 'DOC-LOC-012',
        title: 'Auditoría SRI: Anulación de Comprobantes y Resoluciones',
        level: 'OP',
        durationHours: 6,
        description: 'Manejo de plazos inamovibles, notas de crédito correctivas y cumplimiento de la Resolución NAC-00000014.',
        keyTopics: ['Plazos de anulación', 'Notas de crédito por anulación', 'Pérdida de sustento tributario', 'Régimen sancionatorio'],
      },
      {
        id: 'loc-06',
        code: 'DOC-LOC-028',
        title: 'Formularios SRI (101, 103, 104), ISD 5% y Régimen RIMPE',
        level: 'ARQ',
        durationHours: 8,
        description: 'Cruce contable entre SAP B1 y las declaraciones tributarias oficiales. Tratamiento de RIMPE Negocio Popular y Emprendedor.',
        keyTopics: ['Formulario 104 IVA', 'Formulario 103 Retenciones', 'Impuesto a la Salida de Divisas (ISD)', 'RIMPE parametrizado'],
      },
    ],
  },
  {
    id: 'b1-nom-ec',
    code: 'B1-NOM-EC',
    title: 'B1 Academy Nómina HCM: Motor Laboral & Cumplimiento (IESS/MDT)',
    shortTitle: 'B1 Nómina & IESS',
    category: 'Nómina & Legislación',
    iconName: 'Briefcase',
    badge: 'Nómina HCM + IESS + MDT',
    description: 'Arquitectura y operación de la plataforma B1 Nómina HCM bajo la legislación ecuatoriana: rol de pagos, biométricos, aportes IESS (9.45% / 12.15%), décimos, SBU 2026 ($482), SUT y sincronización con SAP B1.',
    targetAudience: 'Jefes y Analistas de Nómina, Auditores Laborales, Contadores y Consultores de Integración ERP.',
    totalDurationHours: 54,
    submodulesCount: 7,
    submodules: [
      {
        id: 'nom-01',
        code: 'DOC-NOM-024',
        title: 'Novedades, Asistencia y Fórmulas de Horas Extras',
        level: 'OP',
        durationHours: 7,
        description: 'Integración biométrica y cálculo exacto de horas suplementarias (+50%), extraordinarias (+100%) y nocturnas (+25%) sobre base sueldo/240.',
        keyTopics: ['Fórmula Sueldo/240', 'Recargo nocturno 19h00-06h00', 'Horas de descanso obligatorio', 'Importación masiva'],
      },
      {
        id: 'nom-02',
        code: 'DOC-NOM-026',
        title: 'Seguridad Social IESS: Aportes, Fondos de Reserva y Planillas',
        level: 'OP',
        durationHours: 8,
        description: 'Cálculo de materia gravada, aporte personal 9.45%, patronal 11.15% + 1% SECAP/IECE (12.15%), fondos de reserva y planillas TXT.',
        keyTopics: ['Materia gravada vs exenta', 'Préstamos quirografarios/prendarios', 'Avisos de entrada/salida SUT', 'Glosas IESS'],
      },
      {
        id: 'nom-03',
        code: 'DOC-NOM-030',
        title: 'Beneficios Sociales: Décimo Tercero, Décimo Cuarto y Utilidades',
        level: 'OP',
        durationHours: 8,
        description: 'Provisión mensualizada vs acumulada del bono navideño (dic-nov/12), décimo cuarto (SBU $482 según Costa vs Sierra) y 15% utilidades.',
        keyTopics: ['Bono escolar regional', 'SBU 2026 ($482)', '10% individual + 5% cargas familiares', 'Pagos al 15 de marzo / agosto'],
      },
      {
        id: 'nom-04',
        code: 'DOC-NOM-028',
        title: 'Tributación Laboral: Retención Impuesto a la Renta y Anexo RDEP',
        level: 'ARQ',
        durationHours: 8,
        description: 'Proyección anual de ingresos, rebajas por gastos personales con Canasta Familiar Básica (CFB) y generación del anexo RDEP.',
        keyTopics: ['Límite por cargas familiares', 'Fórmula de rebaja CFB', 'Ajuste de fin de año', 'Transmisión RDEP SRI'],
      },
      {
        id: 'nom-05',
        code: 'DOC-NOM-033',
        title: 'Compliance MDT: Actas de Finiquito SUT e Indemnizaciones',
        level: 'ARQ',
        durationHours: 7,
        description: 'Cálculo de liquidaciones según causa: despido intempestivo (Art. 188), desahucio (Art. 185), Visto Bueno (Art. 172) y registro en SUT.',
        keyTopics: ['Plazos legales SUT', 'Cálculo proporcional de décimos', 'Vacaciones no gozadas', 'Bonificación desahucio'],
      },
      {
        id: 'nom-06',
        code: 'DOC-NOM-022',
        title: 'Configuración Maestra: Conceptos, Promedios y Cierre Anual',
        level: 'ARQ',
        durationHours: 8,
        description: 'Caja negra de B1 Nómina HCM: fórmulas de conceptos, bases de promedio para variables salariales y actualización anual del SBU.',
        keyTopics: ['Módulo Conceptos', 'Configuración de Promedios', 'Proceso Cierre/Inicio de Año', 'Auditoría de Nómina'],
      },
      {
        id: 'nom-07',
        code: 'DOC-NOM-054',
        title: 'Interfaz Contable Nómina ↔ SAP Business One (Service Layer)',
        level: 'ARQ',
        durationHours: 8,
        description: 'Mapeo bidireccional entre conceptos salariales y el plan de cuentas de SAP B1 con centros de costo e idempotencia en asientos OJDT/JDT1.',
        keyTopics: ['Mapeo a cuentas de mayor', 'Centros de costo analíticos', 'JSON payloads OData', 'Prevención de duplicidad'],
      },
    ],
  },
  {
    id: 'hein-hcm-talent',
    code: 'B1-HCM-TALENT',
    title: 'B1 Academy Gestión Humana: Desarrollo Organizacional & Matriz Nine Box',
    shortTitle: 'B1 Gestión Humana',
    category: 'Talento & Desempeño',
    iconName: 'Users',
    badge: 'Desarrollo Humano 360°',
    description: 'Gestión integral del ciclo de vida del colaborador: reclutamiento ATS con screening de IA, evaluaciones de desempeño 360°, calibración en la Matriz Nine Box, planes de desarrollo (PDI) y BI de RRHH.',
    targetAudience: 'Directores de Talento Humano, Analistas de Desarrollo Organizacional y Jefes de Área.',
    totalDurationHours: 42,
    submodulesCount: 5,
    submodules: [
      {
        id: 'hcm-01',
        code: 'DOC-RRHH-036',
        title: 'Atracción del Talento: Flujo ATS con Screening de IA',
        level: 'OP',
        durationHours: 8,
        description: 'Publicación de vacantes, filtrado inteligente de hojas de vida mediante algoritmos de IA y seguimiento del candidato.',
        keyTopics: ['Centralización de CVs', 'Algoritmo de screening IA', 'Pipeline de candidatos', 'Contratación'],
      },
      {
        id: 'hcm-02',
        code: 'DOC-RRHH-038',
        title: 'Matrices de Evaluación de Desempeño 90°, 180°, 270° y 360°',
        level: 'ARQ',
        durationHours: 9,
        description: 'Diseño funcional de cuestionarios, ponderación de competencias conductuales/técnicas y evaluación multidimensional.',
        keyTopics: ['Diccionario de competencias', 'Jerarquías de evaluadores', 'Autoevaluación', 'Ciclo anual de desempeño'],
      },
      {
        id: 'hcm-03',
        code: 'DOC-RRHH-040',
        title: 'Analítica del Talento: Calibración y Mapeo en la Matriz Nine Box',
        level: 'ARQ',
        durationHours: 9,
        description: 'Cruce entre Desempeño Operativo y Potencial de Desarrollo. Sesiones de calibración para mitigar el Efecto Halo y planes de sucesión.',
        keyTopics: ['Matriz 9 Box', 'Eje Desempeño vs Potencial', 'Mitigación Efecto Halo', 'Talentos clave y enigmas'],
      },
      {
        id: 'hcm-04',
        code: 'DOC-RRHH-041',
        title: 'Planes de Desarrollo Individual (PDI) y Alineación con OKRs',
        level: 'OP',
        durationHours: 8,
        description: 'Vinculación directa entre las brechas detectadas en la evaluación 360 y las rutas de capacitación continua.',
        keyTopics: ['Rutas de aprendizaje LMS', 'Definición de OKRs', 'Seguimiento de cumplimiento', 'Feedback continuo'],
      },
      {
        id: 'hcm-05',
        code: 'DOC-BI-044',
        title: 'Business Intelligence de RRHH: Rotación, Ausentismo y Pasivos',
        level: 'ARQ',
        durationHours: 8,
        description: 'Dashboards analíticos para control del costo laboral real, cálculo del pasivo vacacional acumulado y causas de desvinculación.',
        keyTopics: ['Cálculo de rotación', 'Índice de ausentismo', 'Auditoría de pasivo vacacional', 'Conexión con SAP B1'],
      },
    ],
  },
  {
    id: 'sap-vert-exp',
    code: 'SAP-VERT-EXP',
    title: 'Verticales de Exportación Ecuador & Add-ons de Boyum IT',
    shortTitle: 'Verticales Banano, Camarón & Beas',
    category: 'Industria & Exportación',
    iconName: 'Award',
    badge: 'Sectores Estratégicos EC',
    description: 'Especialización en las industrias líderes de exportación ecuatoriana: sector bananero (trazabilidad de cajas y GlobalGAP), camaronero (piscinas como centros de costo), manufactura con Beas y WMS Produmex.',
    targetAudience: 'Jefes de Producción, Gerentes de Operaciones, Analistas de Comercio Exterior y Consultores Verticales.',
    totalDurationHours: 50,
    submodulesCount: 6,
    submodules: [
      {
        id: 'vert-01',
        code: 'DOC-IND-016',
        title: 'Vertical Bananera: Trazabilidad de Campo a Empacadora y Exportación',
        level: 'OP',
        durationHours: 9,
        description: 'Control de lotes desde la finca hasta la caja embarcada en puerto. Incorporación de fletes y aranceles al costo del producto.',
        keyTopics: ['Trazabilidad GlobalGAP', 'Costeo de fletes marítimos', 'Liquidación de aduanas', 'Mano de obra agrícola'],
      },
      {
        id: 'vert-02',
        code: 'DOC-IND-018',
        title: 'Vertical Camaronera: Piscinas como Centros de Costo y Biomasa',
        level: 'ARQ',
        durationHours: 9,
        description: 'Configuración arquitectónica de piscinas individuales para segmentar el P&L, consumo de balanceado y costeo por libra cosechada.',
        keyTopics: ['Piscinas como centro de costo', 'Control de biomasa', 'Índice de conversión alimenticia', 'Ciclos de siembra'],
      },
      {
        id: 'vert-03',
        code: 'DOC-IND-014',
        title: 'Manufactura con Beas Manufacturing: Órdenes de Trabajo y Costeo ABC',
        level: 'ARQ',
        durationHours: 9,
        description: 'Planificación avanzada de planta (MES), rutas de producción, captura de piso en tiempo real y costeo por absorción.',
        keyTopics: ['Beas MES para SAP B1', 'Reporte de operarios', 'Control de calidad en línea', 'Costeo por absorción'],
      },
      {
        id: 'vert-04',
        code: 'DOC-IND-038',
        title: 'Gestión Avanzada de Bodegas: Produmex WMS y Radiofrecuencia',
        level: 'ARQ',
        durationHours: 8,
        description: 'Automatización de centros de distribución, picking guiado, captura por radiofrecuencia (Produmex Scan) y cross-docking.',
        keyTopics: ['Produmex WMS', 'Produmex Scan', 'Ubicaciones multizona', 'Etiquetado GS1-128'],
      },
      {
        id: 'vert-05',
        code: 'DOC-SAP-039',
        title: 'Personalización con B1 Usability Package (B1UP) de Boyum IT',
        level: 'ARQ',
        durationHours: 8,
        description: 'Automatización de pantallas, reglas de validación sin código, botones de acción rápida y B1 Print & Delivery.',
        keyTopics: ['Reglas B1UP', 'Validaciones sin código', 'B1 Print & Delivery', 'Mandatory Fields'],
      },
      {
        id: 'vert-06',
        code: 'DOC-SAP-007',
        title: 'Arquitectura de Integración: SAP Service Layer, OData y n8n',
        level: 'ARQ',
        durationHours: 7,
        description: 'Conexión entre SAP B1 y plataformas externas mediante APIs RESTful de alto volumen, payloads JSON y webhooks.',
        keyTopics: ['Service Layer OData', 'Autenticación B1Sessions', 'Colas de mensajes DLQ', 'Webhooks en n8n'],
      },
    ],
  },
];
