/**
 * Banco del examen de certificación por módulo.
 * Cada pregunta trae su rúbrica: los conceptos que una respuesta correcta DEBE cubrir.
 * El evaluador IA califica contra esta rúbrica, no por extensión ni por estilo.
 */
export interface ExamQuestion {
  question: string;
  /** Conceptos obligatorios para obtener el puntaje completo. */
  rubric: string[];
}

export const EXAM_QUESTIONS_PER_ATTEMPT = 5;
export const POINTS_PER_QUESTION = 20;
/** Aprobación: 80/100 en total Y al menos 60 % en cada pregunta (no se aprueba compensando con una sola área fuerte). */
export const PASS_TOTAL = 80;
export const PASS_MIN_PER_QUESTION = 12;
export const MAX_ATTEMPTS_PER_DAY = 3;
export const EXAM_DURATION_MS = 45 * 60_000;
export const MIN_ANSWER_WORDS = 25;

export const EXAM_BANK: Record<string, ExamQuestion[]> = {
  'mod-1': [
    { question: 'Explica la arquitectura de SAP Business One (capas) y qué ocurre técnicamente cuando un usuario inicia sesión y elige una sociedad.', rubric: ['capa de presentación/cliente, capa de aplicación/servidor y capa de base de datos (HANA o SQL Server)', 'cada sociedad es una base de datos independiente', 'el login valida usuario y clave contra la sociedad seleccionada'] },
    { question: '¿Para qué sirve el Cockpit y sus widgets? Da un ejemplo concreto de decisión que un gerente tomaría con un widget.', rubric: ['el cockpit es un tablero personalizable por usuario', 'los widgets muestran KPIs o información en tiempo real', 'ejemplo concreto ligado a una decisión de negocio'] },
    { question: 'Un usuario de ventas pierde tiempo eligiendo siempre el mismo almacén y perfil. ¿Qué configurarías y dónde, y por qué afecta a la calidad de los datos?', rubric: ['configuración de valores por defecto del usuario (parametrizaciones/datos de usuario)', 'almacén predeterminado', 'reduce errores de digitación y estandariza los documentos'] },
    { question: 'Describe al menos tres formas de encontrar información rápidamente en SAP B1 sin navegar todo el menú.', rubric: ['búsqueda/lupa o búsqueda empresarial', 'flecha naranja (vínculo al dato maestro)', 'drag and relate o filtros/búsqueda en formularios'] },
    { question: '¿Qué son las alertas y el buzón de mensajes, y por qué un consultor debe revisarlos al iniciar el día? Da un ejemplo de alerta útil.', rubric: ['las alertas avisan de excepciones o desviaciones (gestión por excepción)', 'el buzón recibe mensajes, alertas y solicitudes de autorización', 'ejemplo concreto (stock mínimo, descuento excedido, aprobación pendiente)'] },
  ],
  'mod-2': [
    { question: 'Diferencia un dato maestro de un documento transaccional y explica qué pasa en los documentos si el maestro de un cliente está mal configurado.', rubric: ['el maestro es permanente y define reglas', 'el documento registra una transacción puntual', 'un error en el maestro se propaga a todos los documentos (precios, condiciones, cuentas)'] },
    { question: '¿Qué datos mínimos y de control configurarías al crear un cliente nuevo en SAP B1 y por qué cada uno importa?', rubric: ['código único y tipo (cliente/proveedor/lead)', 'grupo o cuenta asociada de cuentas por cobrar', 'condiciones de pago, límite de crédito o lista de precios'] },
    { question: 'Explica la diferencia entre un artículo de inventario y un artículo de servicio, y su impacto en la contabilidad.', rubric: ['el de inventario lleva existencias y valoración', 'el servicio no maneja stock', 'el de inventario mueve cuentas de inventario/costo; el servicio va directo a gasto o ingreso'] },
    { question: 'Una empresa compra cajas de 10 unidades pero vende por unidad. ¿Cómo lo resuelves en SAP B1 y qué error evitas?', rubric: ['grupos de unidades de medida', 'UdM de compra distinta de la UdM de venta con factor de conversión', 'evita descuadres de inventario y precios'] },
    { question: '¿Cómo llega automáticamente el precio a una oferta de ventas? Explica el papel de la lista de precios y del socio de negocios.', rubric: ['el artículo tiene precios por lista de precios', 'la lista de precios se asigna al socio de negocios', 'al crear el documento el sistema propone el precio de la lista del cliente'] },
  ],
  'mod-3': [
    { question: 'Describe el ciclo Procure-to-Pay en SAP B1 documento por documento y qué efecto tiene cada uno en inventario y contabilidad.', rubric: ['solicitud/pedido de compra sin efecto contable', 'entrada de mercancías aumenta stock y genera asiento', 'factura de proveedor crea la cuenta por pagar y el pago la cancela'] },
    { question: '¿Qué es el matching de tres vías y qué fraude o error previene?', rubric: ['compara pedido, entrada de mercancías y factura', 'cantidades y precios deben coincidir', 'previene pagar lo no recibido o a precio distinto'] },
    { question: 'Explica cuándo usarías una transferencia de stock y cuándo una entrada o salida de mercancías manual.', rubric: ['transferencia mueve stock entre almacenes sin cambiar el total', 'entradas/salidas manuales cambian el stock total', 'las manuales generan asiento contable contra una cuenta de ajuste'] },
    { question: '¿Cómo harías un recuento de inventario físico en SAP B1 y qué pasa con las diferencias encontradas?', rubric: ['recuento de inventario por almacén/artículos', 'comparación entre cantidad contada y en sistema', 'contabilización de ajuste de diferencias'] },
    { question: '¿Qué diferencia hay entre costo promedio móvil y FIFO, y cuál recomendarías a una distribuidora con precios de compra muy variables?', rubric: ['promedio recalcula el costo con cada entrada', 'FIFO valoriza por capas en orden de entrada', 'recomendación justificada según el negocio'] },
  ],
  'mod-4': [
    { question: 'Describe el ciclo Order-to-Cash completo en SAP B1 y qué documento afecta el inventario y cuál la contabilidad.', rubric: ['oferta → pedido → entrega → factura → cobro', 'la entrega reduce el stock y registra el costo', 'la factura reconoce el ingreso y la cuenta por cobrar'] },
    { question: '¿Para qué sirve el pedido de cliente si todavía no se entrega ni factura? Explica el compromiso de stock.', rubric: ['registra el compromiso con el cliente', 'reserva/compromete cantidades (disponible vs. en stock)', 'permite planificar compras o producción'] },
    { question: 'Un cliente devuelve mercadería ya facturada. ¿Qué documentos usarías y cuál es el efecto en stock y contabilidad?', rubric: ['devolución y/o nota de crédito de clientes', 'reingreso del stock', 'reversa del ingreso y de la cuenta por cobrar'] },
    { question: '¿Qué es una oportunidad de venta y qué información le da a la gerencia comercial?', rubric: ['seguimiento de un negocio potencial por etapas', 'monto potencial y probabilidad de cierre', 'pronóstico del pipeline de ventas'] },
    { question: 'Explica cómo se copia un documento a otro (Copiar a / Copiar de) y por qué es importante para la trazabilidad.', rubric: ['funciones copiar a / copiar desde', 'los documentos quedan vinculados', 'se puede auditar el flujo completo y evita digitar dos veces'] },
  ],
  'mod-5': [
    { question: 'Explica la jerarquía de determinación de precios en SAP B1: ¿qué precio gana cuando hay precio especial, descuento por período y lista de precios?', rubric: ['precios especiales por socio de negocios tienen prioridad', 'luego descuentos por período/volumen', 'por último la lista de precios'] },
    { question: '¿Cómo configurarías un descuento por volumen (a mayor cantidad, menor precio) y para qué tipo de cliente?', rubric: ['descuentos por período y volumen', 'escalas de cantidad con precio o porcentaje', 'aplicación a una lista o socio específico'] },
    { question: '¿Qué son los grupos de descuento y en qué se diferencian de un precio especial?', rubric: ['descuento aplicado a grupos de artículos o fabricantes', 'se asigna a un cliente o grupo de clientes', 'el precio especial es por artículo y socio concreto'] },
    { question: 'Explica cómo crear una lista de precios derivada de otra (por ejemplo, distribuidores = base menos 10 %).', rubric: ['lista basada en otra lista', 'factor o porcentaje', 'se actualiza al cambiar la base'] },
    { question: '¿Qué riesgo financiero tiene dar descuentos sin control y qué mecanismo de SAP B1 lo evita?', rubric: ['pérdida de margen', 'procedimientos de autorización o alertas por descuento excedido', 'control por usuario/límites'] },
  ],
  'mod-6': [
    { question: '¿Qué es una llamada de servicio y qué información registra desde que el cliente reporta hasta que se cierra?', rubric: ['registro del problema del cliente', 'técnico asignado, actividades y tiempos', 'solución y cierre con historial'] },
    { question: '¿Qué es una tarjeta de equipo y cómo se genera automáticamente?', rubric: ['registro del equipo vendido con número de serie', 'se crea al entregar artículos con número de serie', 'vincula cliente, garantía e historial'] },
    { question: '¿Para qué sirve la base de soluciones y cómo ahorra tiempo al área de soporte?', rubric: ['repositorio de soluciones conocidas', 'se reutiliza en nuevas llamadas', 'reduce tiempo de resolución'] },
    { question: 'Explica cómo un contrato de servicio o garantía define si una reparación se cobra o no.', rubric: ['contrato con cobertura (piezas, mano de obra, viaje)', 'vigencia', 'lo no cubierto se factura'] },
    { question: '¿Qué indicadores de servicio presentarías a la gerencia y de dónde salen?', rubric: ['tiempo de respuesta/resolución', 'llamadas abiertas vs cerradas o por técnico', 'informes del módulo de servicio'] },
  ],
  'mod-7': [
    { question: 'Explica la estructura de un plan de cuentas y la diferencia entre cuentas de título y cuentas activas.', rubric: ['estructura jerárquica por niveles (activo, pasivo, patrimonio, ingresos, gastos)', 'cuentas de título agrupan', 'solo las cuentas activas reciben movimientos'] },
    { question: '¿Qué asientos genera SAP B1 automáticamente en una factura de deudores de un artículo de inventario? Detalla débitos y créditos.', rubric: ['débito a cuentas por cobrar del cliente', 'crédito a ingresos y a IVA por pagar', 'si la entrega no existía: costo de ventas contra inventario'] },
    { question: '¿Cuándo es correcto registrar un asiento manual y qué controles debería tener?', rubric: ['ajustes, provisiones o reclasificaciones sin documento de origen', 'debe cuadrar débito = crédito', 'referencia, comentario y autorización/revisión'] },
    { question: 'Explica para qué sirven las cuentas de mayor por defecto (determinación de cuentas) y qué pasa si están mal configuradas.', rubric: ['definen qué cuentas usan automáticamente los documentos', 'por artículo, grupo o almacén', 'mala configuración = contabilización errónea masiva'] },
    { question: '¿Qué son las diferencias de cambio y cuándo debe ejecutarse su ajuste?', rubric: ['saldos en moneda extranjera revaluados al tipo de cambio actual', 'genera ganancia o pérdida por diferencia de cambio', 'se ejecuta al cierre de período'] },
  ],
  'mod-8': [
    { question: 'Describe cómo registrar un pago recibido de un cliente que paga dos facturas con una transferencia, y qué asiento resulta.', rubric: ['pago recibido seleccionando las facturas', 'medio de pago transferencia a cuenta bancaria', 'débito a banco y crédito a cuentas por cobrar'] },
    { question: '¿Qué medios de pago maneja SAP B1 y qué diferencia contable tiene un cheque recibido frente a una transferencia?', rubric: ['efectivo, cheque, transferencia, tarjeta', 'el cheque puede pasar por una cuenta transitoria hasta el depósito', 'la transferencia va directo a la cuenta bancaria'] },
    { question: 'Explica la conciliación bancaria: qué se compara, qué son las partidas conciliatorias y por qué es un control clave.', rubric: ['compara extracto bancario con libros', 'partidas en tránsito o no registradas', 'detecta errores, fraudes u omisiones'] },
    { question: '¿Qué es la reconciliación interna de cuentas y en qué se diferencia de la conciliación bancaria?', rubric: ['empareja débitos y créditos dentro de una cuenta (p. ej. cliente)', 'deja saldos abiertos correctos', 'no involucra extracto bancario'] },
    { question: '¿Cómo usarías el asistente de pagos para pagar a varios proveedores y qué riesgo controla?', rubric: ['selección masiva de facturas por vencimiento/criterios', 'generación de pagos en lote', 'control de flujo de caja y de pagos duplicados'] },
  ],
  'mod-9': [
    { question: '¿Qué datos configuras en el maestro de un activo fijo y por qué la clase de activo es importante?', rubric: ['clase de activo, vida útil, método de amortización', 'la clase define cuentas y parámetros por defecto', 'fecha de capitalización/valor'] },
    { question: 'Explica la capitalización de un activo comprado a un proveedor y su asiento.', rubric: ['capitalización desde factura o documento de capitalización', 'débito a activo fijo', 'crédito a proveedor o cuenta de compensación'] },
    { question: '¿Cómo se ejecuta la amortización mensual y qué asiento genera?', rubric: ['ejecución de amortización por período', 'débito a gasto de amortización', 'crédito a amortización acumulada'] },
    { question: 'Un activo se vende antes de terminar su vida útil. ¿Qué proceso sigues y cómo se determina la ganancia o pérdida?', rubric: ['retiro o venta del activo', 'valor neto en libros = costo - amortización acumulada', 'diferencia con el precio de venta = ganancia o pérdida'] },
    { question: '¿Qué informe usarías para presentar al auditor el estado de los activos fijos?', rubric: ['historial o listado de activos', 'valor de adquisición, amortización acumulada y valor neto', 'movimientos del período'] },
  ],
  'mod-10': [
    { question: 'Explica qué es el MRP y qué datos de entrada necesita para calcular necesidades.', rubric: ['planificación de necesidades de materiales', 'demanda: pedidos de cliente y/o pronósticos', 'stock, pedidos abiertos, listas de materiales y plazos'] },
    { question: '¿Para qué sirve un pronóstico y cómo se combina con los pedidos reales en el MRP?', rubric: ['estima demanda futura', 'se consume con pedidos reales para no duplicar', 'permite planificar antes de recibir pedidos'] },
    { question: 'Describe el asistente MRP paso a paso hasta obtener recomendaciones.', rubric: ['escenario: horizonte y artículos', 'fuentes de datos y almacenes', 'ejecución y revisión de recomendaciones'] },
    { question: '¿Qué hace un usuario con las recomendaciones del MRP?', rubric: ['revisarlas y ajustar', 'convertir en pedidos de compra u órdenes de fabricación', 'controlar los plazos'] },
    { question: '¿Qué ocurre si los plazos de entrega (lead time) de los artículos están mal definidos?', rubric: ['fechas de pedido erróneas', 'faltantes o exceso de inventario', 'el MRP solo es tan bueno como sus datos maestros'] },
  ],
  'mod-11': [
    { question: 'Explica los tipos de lista de materiales (producción, montaje, venta, plantilla) y cuándo usar cada uno.', rubric: ['producción: fabricación con orden', 'montaje/venta: se expande en el documento de venta', 'plantilla: sugerencia modificable'] },
    { question: 'Describe el ciclo de una orden de fabricación desde planificada hasta cerrada.', rubric: ['planificada → liberada → cerrada', 'emisión de componentes', 'recibo del producto terminado y cierre'] },
    { question: '¿Qué asientos generan la emisión para producción y el recibo de producción?', rubric: ['emisión: crédito a inventario de materias primas, débito a producción en proceso (WIP)', 'recibo: débito a inventario de producto terminado', 'diferencias de costo al cerrar la orden'] },
    { question: '¿Cómo calcularías el costo real de fabricar una unidad en SAP B1?', rubric: ['costo de componentes emitidos', 'recursos/mano de obra/costos adicionales', 'dividido entre la cantidad recibida'] },
    { question: '¿Qué es un proyecto en SAP B1 y cómo ayuda a medir la rentabilidad por proyecto?', rubric: ['código de proyecto en documentos y asientos', 'agrupa ingresos y costos', 'informes de rentabilidad por proyecto'] },
  ],
  'mod-12': [
    { question: '¿Qué es el gestor de consultas (Query Manager) y qué precauciones de seguridad tomarías al dar acceso?', rubric: ['crea y guarda consultas SQL sobre las tablas', 'consultas de solo lectura y autorizaciones por usuario', 'riesgo de exponer datos sensibles'] },
    { question: 'Escribe en palabras (o SQL) una consulta para listar facturas de clientes abiertas con su saldo. ¿Qué tablas usarías?', rubric: ['tabla de facturas OINV (y líneas INV1 si aplica)', 'filtro de documentos abiertos (DocStatus = O)', 'saldo = total - pagado'] },
    { question: '¿Para qué sirve Data Transfer Workbench y qué pasos sigues para migrar maestros de clientes?', rubric: ['herramienta de importación masiva', 'plantillas con estructura de tablas', 'simulación/prueba y luego importación con revisión de errores'] },
    { question: '¿Cómo crearías una alerta personalizada basada en una consulta? Da un ejemplo de negocio.', rubric: ['consulta guardada como base', 'gestión de alertas con frecuencia y destinatarios', 'ejemplo concreto (stock bajo, facturas vencidas)'] },
    { question: 'Un cliente pide un campo que SAP B1 no trae. ¿Qué opciones tienes antes de programar?', rubric: ['campos definidos por el usuario (UDF)', 'valores definidos por el usuario / búsquedas formateadas', 'evitar desarrollos cuando la configuración basta'] },
  ],
  'mod-13': [
    { question: '¿Cuál es la diferencia fundamental entre una factura de compra tipo artículo y tipo servicio, y cómo impacta en inventario y contabilidad?', rubric: ['el tipo artículo mueve stock y valoración de inventario', 'el tipo servicio no mueve stock y se imputa directamente a cuenta de mayor/gasto', 'ambos generan cuenta por pagar al proveedor'] },
    { question: 'Describe el proceso de Solicitud de Cotización de Compra (RFQ) y cómo SAP B1 permite comparar las ofertas de diferentes proveedores.', rubric: ['solicitud de cotización enviada a múltiples proveedores', 'registro de precios y condiciones ofrecidas', 'informe comparativo de cotizaciones para seleccionar la mejor opción'] },
    { question: 'Un proveedor entrega mercadería defectuosa que ya había ingresado al almacén con Entrada de Mercancías. ¿Qué documento se emite y qué efecto contable y de stock tiene?', rubric: ['documento de devolución de mercancías', 'disminuye el stock del almacén', 'revierte el asiento provisional de cuenta de compensación de compras/inventario'] },
    { question: 'Explica la diferencia entre una Solicitud de Anticipo de Proveedor y una Factura de Anticipo de Proveedor.', rubric: ['la solicitud de anticipo no genera asiento contable, solo compromiso', 'la factura de anticipo genera asiento contable de cuenta de anticipos contra banco/proveedor', 'el anticipo se deduce al pagar la factura definitiva'] },
    { question: '¿Qué controles internos deben existir antes de aprobar una factura de compra de servicios sin orden de compra previa?', rubric: ['verificación de autorización por centro de costo o gerencia', 'comprobación del servicio efectivamente prestado (acta de entrega-recepción)', 'revisión de retenciones aplicables e impuestos'] },
  ],
  'mod-14': [
    { question: 'Compara los métodos de valoración de inventario en SAP B1: Promedio Ponderado, FIFO y Precio Estándar.', rubric: ['promedio recalcula costo con cada entrada ponderando cantidad y precio', 'FIFO consume capas de stock en orden cronológico de entrada', 'precio estándar fija un costo teórico y desvía diferencias a cuenta de variación'] },
    { question: '¿Qué es una Revalorización de Inventario y en qué situaciones de negocio está justificado aplicarla?', rubric: ['ajuste directo del costo unitario o del valor total del stock', 'genera asiento contra cuenta de pérdidas/ganancias por revalorización', 'justificado por mermas, deterioro de valor de mercado o corrección de costos erróneos'] },
    { question: 'Explica el proceso de Costos de Importación (Precios de Entrega / Landed Costs) en compras internacionales.', rubric: ['distribuye fletes, aranceles, seguros y gastos aduaneros sobre el valor de los artículos', 'reparte por valor, peso, volumen o importe', 'incrementa el costo unitario real en inventario'] },
    { question: '¿Qué es el sistema de inventario permanente (continuo) en SAP B1 y qué cuentas de mayor mueve en cada compra y venta?', rubric: ['actualización en tiempo real de saldos contables de stock', 'compra: débito a inventario y crédito a proveedor/cuenta puente', 'venta: débito a costo de ventas y crédito a inventario'] },
    { question: '¿Cómo afecta la elección del método de valoración al margen bruto y al impuesto a la renta en un entorno inflacionario?', rubric: ['en inflación FIFO reporta menor costo de venta y mayor utilidad contable/tributaria', 'promedio ponderado suaviza las fluctuaciones', 'la normativa fiscal local (SRI) regula qué métodos son aceptados'] },
  ],
  'mod-15': [
    { question: 'Explica la estructura jerárquica de Ubicaciones (Bin Locations) en un almacén administrado en SAP B1.', rubric: ['subniveles: pasillo, estante, nivel y casilla/ubicación física', 'permite control exacto de dónde reside cada artículo', 'optimiza tiempos de almacenaje y recolección'] },
    { question: 'Describe el flujo completo de Recuento de Inventario Físico en SAP B1 y el tratamiento de faltantes y sobrantes.', rubric: ['generación de documento de recuento e inmovilización/bloqueo de artículos', 'registro de cantidades contadas por el personal de bodega', 'contabilización de diferencias afectando cuentas de ajuste de inventario'] },
    { question: '¿Cuál es la diferencia operativa y contable entre una Transferencia de Stock entre almacenes y una Solicitud de Traslado?', rubric: ['la solicitud de traslado es una reserva o intención sin movimiento físico ni contable', 'la transferencia de stock mueve físicamente las existencias', 'si los almacenes tienen distinta valoración o cuenta contable, genera asiento'] },
    { question: '¿Cómo gestiona SAP B1 el stock en tránsito cuando un camión tarda varios días en viajar de una sucursal a otra?', rubric: ['uso de un almacén virtual de tránsito', 'salida del almacén origen hacia tránsito y posterior recepción en destino', 'mantiene la propiedad contable de la mercadería durante el transporte'] },
    { question: '¿Qué criterios y documentación debe registrar un consultor al tramitar una baja de inventario por caducidad o merma extraordinaria?', rubric: ['salida de mercancías manual con motivo documentado', 'imputación a cuenta de gasto por pérdida o deterioro de inventario', 'cumplimiento del acta notariada o informe técnico exigido por la normativa fiscal'] },
  ],
  'mod-16': [
    { question: 'Explica el ciclo del Gestor de Picking y Embalaje (Pick and Pack Manager) en SAP Business One.', rubric: ['tres estados: liberado para picking, en picking y embalado', 'creación de la lista de preparación de pedidos para bodega', 'conversión final en entrega de clientes o factura de reserva'] },
    { question: '¿Cómo optimiza el Pick and Pack el despacho cuando existen cientos de pedidos de venta diarios?', rubric: ['permite agrupamiento por cliente, ruta, fecha o zona de almacén', 'recolección consolidada (batch picking) para reducir traslados', 'valida disponibilidad de stock antes de liberar pedidos'] },
    { question: 'Describe cómo se asegura la trazabilidad de números de serie y lotes al momento de generar la Entrega en ventas.', rubric: ['asignación obligatoria de lotes o series específicos en la línea de despacho', 'registro de fechas de vencimiento para cumplir con política FEFO/FIFO', 'la entrega queda vinculada al pedido y al historial del lote'] },
    { question: '¿Qué función cumple la Guía de Remisión Electrónica en Ecuador y qué datos de SAP B1 deben alimentar este documento?', rubric: ['comprobante legal de traslado de mercaderías emitido ante el SRI', 'datos del transportista, vehículo (placa), punto de partida y llegada', 'vinculación con la factura o entrega de clientes'] },
    { question: '¿Qué sucede si un cliente rechaza parte del pedido en el momento exacto de la entrega física en su bodega?', rubric: ['se puede registrar la entrega solo por la cantidad aceptada', 'la cantidad no entregada queda pendiente en el pedido original', 'o se emite una devolución de clientes si la entrega ya estaba cerrada'] },
  ],
  'mod-17': [
    { question: '¿Cómo se genera el Balance General en SAP B1 y qué representan los diferentes niveles del plan de cuentas?', rubric: ['muestra activo, pasivo y patrimonio a una fecha de corte', 'los niveles superiores corresponden a cuentas de título de agrupación', 'el nivel más bajo muestra las cuentas imputables activas con saldo'] },
    { question: 'Explica la diferencia entre el Estado de Resultados (Pérdidas y Ganancias) por período y el acumulado anual.', rubric: ['refleja ingresos, costos y gastos operativos del período seleccionado', 'determina la utilidad o pérdida neta antes y después de impuestos', 'se reinicia a cero al inicio del nuevo ejercicio fiscal mediante el cierre anual'] },
    { question: '¿Qué es el informe de Flujo de Caja en SAP B1 y cómo incorpora datos previstos además de los movimientos reales?', rubric: ['proyección de liquidez y disponibilidades financieras', 'integra saldos bancarios actuales con pedidos abiertos y facturas por cobrar/pagar', 'permite añadir operaciones previsionales recurrentes no contabilizadas'] },
    { question: '¿Para qué sirve el Balance de Comprobación (Sumas y Saldos) y cómo ayuda a detectar errores contables?', rubric: ['lista todas las cuentas de mayor con débitos, créditos y saldo resultante', 'verifica que la suma total de débitos sea exactamente igual a los créditos', 'permite auditar cuentas con saldos contra-natura o descuadres'] },
    { question: '¿Cómo gestiona SAP B1 los informes financieros cuando la empresa opera con transacciones en múltiples monedas?', rubric: ['cada transacción registra importe en moneda local, moneda del sistema y moneda extranjera', 'los informes pueden emitirse en cualquiera de las tres monedas', 'las diferencias de tipo de cambio se ajustan en cuentas específicas'] },
  ],
  'mod-18': [
    { question: 'Explica el concepto de Dimensiones y Normas de Reparto en la contabilidad de costes de SAP Business One.', rubric: ['dimensiones permiten separar ejes de análisis (ej. departamentos, líneas de negocio, proyectos)', 'normas de reparto definen porcentajes de distribución de costos', 'se imputan en líneas de documentos operativos y asientos'] },
    { question: '¿Cómo se asigna un centro de costo en un documento de compras y qué informe muestra el gasto acumulado por centro?', rubric: ['asignación de centro de costo en la línea del artículo o servicio', 'contabilización con código analítico en el asiento generado', 'informe de contabilidad de costes / balance de centros de costo'] },
    { question: 'Describe cómo se configura un escenario presupuestario en SAP B1 y cuáles son los métodos de distribución permitidos.', rubric: ['definición de presupuesto anual por cuenta de mayor contable', 'métodos de distribución lineal, estacional o porcentual mensual', 'vinculación con el escenario presupuestario principal'] },
    { question: '¿Qué mecanismos de control presupuestario ofrece SAP B1 cuando un usuario intenta superar el presupuesto asignado?', rubric: ['alertas o bloqueos automáticos al crear pedidos o facturas', 'configuración de advertencia o bloqueo estricto por usuario', 'control a nivel anual o mensual'] },
    { question: '¿Qué información entrega el informe comparativo Presupuesto vs Real a la gerencia financiera?', rubric: ['compara el monto presupuestado contra el gasto o ingreso real ejecutado', 'muestra la desviación absoluta en moneda y porcentual', 'permite tomar acciones correctivas antes del cierre de ejercicio'] },
  ],
  'mod-19': [
    { question: 'Explica la estructura y generación de la clave de acceso de 49 dígitos en los comprobantes electrónicos del SRI de Ecuador.', rubric: ['49 dígitos que identifican unívocamente el comprobante', 'incluye fecha, tipo de documento, RUC emisor, ambiente, serie y secuencial', 'incorpora código numérico aleatorio y dígito verificador módulo 11'] },
    { question: '¿Cuáles son los tipos de comprobantes electrónicos vigentes en Ecuador y cómo se firman digitalmente?', rubric: ['facturas, notas de crédito, notas de débito, retenciones y guías de remisión', 'archivo XML estructurado según esquema XSD del SRI', 'firma electrónica formato XAdES-BES con certificado digital .p12'] },
    { question: 'Describe el flujo de autorización de un comprobante electrónico ante los Web Services del SRI (Offline).', rubric: ['generación y firmado local del XML', 'envío al web service de recepción del SRI', 'consulta del estado en el web service de autorización y obtención de número de autorización'] },
    { question: '¿Qué es un comprobante de retención electrónico, qué plazos existen para emitirlo y qué impuestos grava?', rubric: ['documento emitido por el comprador como agente de retención', 'plazo de emisión máximo de 5 días desde la fecha de factura', 'retenciones en la fuente de Impuesto a la Renta e Impuesto al Valor Agregado (IVA)'] },
    { question: '¿Qué es el Anexo Transaccional Simplificado (ATS) y cómo asegura el cuadre entre compras, ventas y retenciones?', rubric: ['anexo XML mensual de todas las compras, ventas, retenciones y anulados reportado al SRI', 'valida el crédito tributario de IVA y retenciones practicadas', 'debe cuadrar con el formulario 104 de IVA y formulario 103 de retenciones'] },
  ],
  'mod-20': [
    { question: '¿Qué es un Recurso en el módulo de producción de SAP B1 y en qué se diferencia de un Artículo?', rubric: ['el recurso representa capacidad (máquina, mano de obra, herramienta)', 'no maneja stock físico sino disponibilidad de tiempo o costo por hora', 'se vincula a cuentas de mayor de costes indirectos y mano de obra'] },
    { question: 'Explica cómo se define la capacidad diaria y de período para una máquina en el calendario de producción.', rubric: ['definición de horas disponibles por día de trabajo', 'calendario de fábrica excluyendo fines de semana y feriados', 'permite evaluar sobrecarga o subutilización de la maquinaria'] },
    { question: 'Describe una Ruta de Producción (Routing) y para qué sirven las etapas de producción en una orden de fabricación.', rubric: ['secuencia ordenada de pasos o etapas para fabricar un producto', 'cada etapa consume recursos y componentes específicos', 'permite medir el avance parcial de la producción'] },
    { question: '¿Cómo impactan los tiempos de preparación (setup time) y tiempos de ejecución (run time) en la programación de la fábrica?', rubric: ['tiempo de preparación fijo independiente de la cantidad a producir', 'tiempo de ejecución proporcional al volumen de unidades', 'afectan la fecha estimada de entrega y el coste del lote'] },
    { question: '¿Qué ocurre contablemente al cerrar una orden de fabricación cuando los costes reales difieren de los estimados?', rubric: ['liquidación de la cuenta de producción en proceso (WIP)', 'desviación de costes imputada a cuenta de variación de producción', 'el coste final del producto terminado queda ajustado'] },
  ],
  'mod-21': [
    { question: 'Explica la administración de usuarios, asignación de licencias y perfiles de autorización en SAP Business One.', rubric: ['creación de códigos de usuario y claves seguras', 'asignación de licencia nominal (Profesional, CRM, Financiera, Logística)', 'configuración de autorizaciones detalladas (sin autorización, solo lectura, autorización total)'] },
    { question: '¿Qué es el Log de Modificaciones (Change Log) y cómo apoya las auditorías forenses en la empresa?', rubric: ['historial de cambios campo por campo en maestros y documentos', 'registra usuario, fecha, hora y valor anterior vs nuevo', 'garantiza no repudio y trazabilidad de alteraciones'] },
    { question: 'Describe la política de respaldos (backups) recomendada para SAP Business One en entornos HANA y SQL Server.', rubric: ['respaldos completos diarios y de logs transaccionales periódicos', 'almacenamiento en servidores o ubicaciones secundarias seguras', 'pruebas periódicas de restauración de base de datos'] },
    { question: '¿Cómo se bloquea un período contable cerrado en SAP B1 para evitar que usuarios registren transacciones con fecha anterior?', rubric: ['gestión de períodos contables en inicialización del sistema', 'cambio de estado a "Cerrado" o "Cierre de período"', 'impide crear asientos o documentos con fechas fuera del rango permitido'] },
    { question: '¿Qué precauciones de seguridad debe tomar un administrador de sistemas al otorgar permisos de acceso a la base de datos y al Query Manager?', rubric: ['restringir acceso SQL directo a usuarios operativos', 'autorizaciones granulares para ejecutar consultas sin exponer salarios ni datos sensibles', 'evitar el uso de credenciales maestras (manager/sa) en el trabajo diario'] },
  ],
  'mod-22': [
    { question: 'Explica la diferencia entre Tablas Definidas por el Usuario (UDT) tipo Datos Maestros y tipo Sin Objeto.', rubric: ['datos maestros incluyen código y nombre con pantalla nativa de mantenimiento', 'sin objeto son tablas planas para almacenar logs o datos auxiliares', 'se crean desde Herramientas > Herramientas de personalización'] },
    { question: '¿Qué es un Campo Definido por el Usuario (UDF) y en qué tablas de SAP B1 se puede incorporar?', rubric: ['campo adicional personalizado agregado a tablas estándar (OINV, OCRD, OITM, etc.)', 'soporta tipos alfanumérico, numérico, fecha y valores válidos de lista desplegable', 'permite almacenar información específica del negocio sin alterar el core del ERP'] },
    { question: 'Describe la herramienta Pervasive Analytics en SAP HANA y los tipos de objetos analíticos que permite construir.', rubric: ['plataforma integrada de business intelligence en SAP Business One HANA', 'permite diseñar Dashboards interactivos y KPIs en tiempo real', 'se colocan directamente en el Cockpit de los usuarios según su rol'] },
    { question: '¿Cómo se vincula un Dashboard de Pervasive Analytics a una ventana de documento para mostrar analítica contextual?', rubric: ['asociación del dashboard con el formulario transaccional (ej. socio de negocios)', 'filtra los datos analíticos usando el código del registro activo en pantalla', 'proporciona información de toma de decisiones en el punto de contacto'] },
    { question: '¿Qué ventajas ofrecen las Vistas de Cálculo (Calculation Views) de SAP HANA frente a consultas SQL tradicionales?', rubric: ['procesamiento masivo en memoria RAM (in-memory computing)', 'modelado multidimensional con jerarquías y medidas agregadas', 'rendimiento instantáneo al consultar millones de registros transaccionales'] },
  ],
  'mod-23': [
    { question: 'Describe el proceso de preparación y carga de datos maestros con Data Transfer Workbench (DTW).', rubric: ['uso de plantillas CSV oficiales con prefijos de tabla (OCRD, CRD1, etc.)', 'limpieza y homologación previa de datos en hojas de cálculo', 'modo de simulación para validar errores antes de la carga real definitiva'] },
    { question: '¿Cómo se efectúa la carga de saldos iniciales de contabilidad al migrar a SAP Business One desde otro sistema?', rubric: ['asiento de apertura cuadrado contra cuenta puente de saldos iniciales', 'respeto de saldos de clientes y proveedores con sus números de factura histórica', 'verificación de que el balance general inicial coincida exactamente con el sistema anterior'] },
    { question: 'Explica los pasos para cargar los saldos iniciales de inventario y valorar las existencias iniciales.', rubric: ['documento de saldos iniciales de inventario por almacén', 'asignación de costo unitario según el método de valoración de la empresa', 'asiento generado contra cuenta de compensación de saldos de apertura'] },
    { question: '¿Qué es el Plan de Corte (Cutover Plan) y qué actividades críticas comprende durante el fin de semana de Go-Live?', rubric: ['cronograma hora por hora de congelamiento de operaciones en el sistema anterior', 'extracción final de datos, migración, parametrización y cuadres contables', 'pruebas de humo (smoke tests) y autorización formal para el arranque en vivo'] },
    { question: '¿En qué consiste el período de Hypercare y cuáles son las responsabilidades del equipo de consultoría durante esta fase?', rubric: ['soporte intensivo post-salida en vivo durante las primeras 2 a 4 semanas', 'resolución prioritaria de incidencias operativas y estabilización de usuarios', 'acompañamiento en el primer cierre contable mensual y traspaso a soporte continuo'] },
  ],
  'mod-24': [
    { question: 'En un proyecto integrador SAP B1, describe cómo fluye la información desde la cotización de venta hasta el cobro bancario final.', rubric: ['oferta comercial → pedido de cliente → entrega con reserva de stock → factura electrónica', 'cobro recibido con depósito bancario y conciliación', 'trazabilidad completa y mapa de relaciones del documento'] },
    { question: '¿Cómo interactúan las compras, el inventario y la contabilidad durante el ciclo completo de aprovisionamiento en una empresa comercial?', rubric: ['pedido de compra → recepción de mercadería (aumenta stock) → factura de proveedor (crea cuenta por pagar)', 'pago efectuado al proveedor con comprobante de retención SRI', 'imputación contable exacta sin descuadres de inventario'] },
    { question: 'Describe la ejecución de una orden de producción que requiere materias primas importadas y recursos de mano de obra.', rubric: ['emisión de materias primas a la orden (reducción de stock de insumos)', 'registro de tiempos y costes de recursos humanos/máquina', 'recibo del producto terminado y posterior costeo real del lote fabricado'] },
    { question: '¿Qué controles contables y fiscales deben verificarse antes de dar por cerrado con éxito el ejercicio en el proyecto integrador?', rubric: ['cuadre de balance de sumas y saldos y ausencia de cuentas puente desbalanceadas', 'conciliación bancaria al 100% y comprobación de retenciones SRI', 'verificación de que el inventario contable coincida con el inventario físico valorado'] },
    { question: '¿Cómo evalúa la gerencia y el auditor que una implementación de SAP Business One fue exitosa y generó retorno de inversión?', rubric: ['reducción de tiempos de ciclo operativo y eliminación de retrabajos en hojas de cálculo', 'disponibilidad de información financiera confiable en tiempo real', 'trazabilidad total de operaciones y cumplimiento fiscal sin contingencias'] },
  ],
  'mod-25': [
    { question: 'Explica los componentes legales y porcentajes del aporte al IESS en el rol de pagos de Ecuador vigente en 2026.', rubric: ['aporte personal del trabajador: 9.45% descontado del salario bruto', 'aporte patronal de la empresa: 11.15% asumido por el empleador', 'fondos de reserva: 8.33% aplicable a partir del segundo año de labores'] },
    { question: 'Describe el tratamiento y cálculo de la Decimotercera y Decimocuarta remuneración bajo la legislación laboral ecuatoriana.', rubric: ['decimotercero: doceava parte de todo lo ganado en el año calendario laboral', 'decimocuarto: un salario básico unificado (SBU 2026: $460 USD) prorrateado', 'opción del colaborador de mensualizar o acumular en las fechas legales'] },
    { question: '¿Cómo se liquidan las Horas Suplementarias (50%) y Horas Extraordinarias (100%) en el rol de pagos mensual?', rubric: ['suplementarias (recargo 50%): días ordinarios hasta las 24h00', 'extraordinarias (recargo 100%): fines de semana, feriados o entre 24h00 y 06h00', 'fórmula basada en el valor de la hora ordinaria (sueldo dividido para 240 horas)'] },
    { question: 'Detalla el asiento contable de devengo de nómina mensual en SAP B1 indicando las cuentas deudoras y acreedoras.', rubric: ['débito a cuentas de gasto: sueldos, horas extras, beneficios sociales y aporte patronal', 'crédito a pasivos: sueldos por pagar, IESS por pagar y retenciones judiciales/fiscales', 'cuadre perfecto de la provisión contable de la nómina'] },
    { question: '¿Qué archivo o estructura debe generarse en el módulo de nómina para el pago masivo en bancos y la planilla de aportes al IESS?', rubric: ['archivo plano bancario para acreditación de haberes en cuentas de empleados', 'archivo para carga de planilla de aportes en el portal del IESS', 'comprobante de retención de impuesto a la renta en relación de dependencia (Formulario 107)'] },
  ],
  'mod-26': [
    { question: 'Describe las seis fases de la metodología SAP Activate y el objetivo fundamental de cada una en proyectos de ERP.', rubric: ['Discover (estrategia y alcance), Prepare (kick-off y equipo), Explore (talleres Fit/Gap)', 'Realize (parametrización y migraciones), Deploy (cutover y go-live), Run (operación y soporte continuo)', 'metodología ágil combinada con mejores prácticas preconfiguradas'] },
    { question: '¿Qué es un Taller de Exploración (Explore Phase) y cómo se realiza un Análisis Fit / Gap?', rubric: ['confrontación de los procesos de la empresa contra las mejores prácticas de SAP', 'identificación de puntos coincidentes (Fit) y diferencias o brechas (Gap)', 'documentación de cómo se resolverán los gaps: configuración, desarrollo o cambio de proceso'] },
    { question: '¿Cuál es la función de la Golden DB (Base de Datos Maestra de Configuración) en la fase de Realización?', rubric: ['base de datos limpia donde se configuran y prueban todos los parámetros', 'fuente única de verdad para replicar a ambientes de prueba (QA) y producción (PRD)', 'evita que datos ficticios de prueba contaminen la configuración final'] },
    { question: 'Explica qué es un Cutover Runbook y por qué es un instrumento crítico para el éxito del Go-Live.', rubric: ['plan detallado paso a paso con responsables, horas estimadas y dependencias', 'secuencia de parada de sistemas legados, extracción final y carga en SAP B1', 'permite coordinar al equipo técnico y de negocio sin improvisaciones'] },
    { question: '¿Qué son los Quality Gates (Puertas de Calidad) en SAP Activate y qué ocurre si un proyecto no supera una puerta?', rubric: ['hitos formales de validación al final de cada fase', 'revisión de entregables completados, riesgos mitigados y aprobación de stakeholders', 'no se autoriza el paso a la siguiente fase hasta resolver las no conformidades'] },
  ],
  'mod-27': [
    { question: 'Explica los componentes esenciales de la notación BPMN 2.0: Pools, Lanes, Tareas, Eventos y Compuertas.', rubric: ['Pool representa la organización o proceso; Lanes representan roles o departamentos', 'Tareas son acciones realizadas; Eventos marcan inicio, intermedio o fin', 'Compuertas controlan la bifurcación y unión del flujo según condiciones'] },
    { question: '¿Por qué es indispensable levantar el modelo AS-IS antes de parametrizar SAP Business One en un cliente?', rubric: ['permite entender la realidad operativa actual y las ineficiencias del cliente', 'identifica cuellos de botella, reprocesos y hojas de cálculo no controladas', 'establece la línea base para medir las mejoras del nuevo sistema'] },
    { question: 'Describe el proceso de diseño del modelo TO-BE y cómo debe alinearse a las Mejores Prácticas de SAP.', rubric: ['diseño del flujo futuro estandarizado y optimizado', 'adopción de la lógica transaccional estándar de SAP B1 para minimizar desarrollos', 'eliminación de pasos innecesarios y automatización de controles'] },
    { question: '¿Cómo se traduce una compuerta lógica exclusiva (XOR) de BPMN a un Procedimiento de Aprobación en SAP B1?', rubric: ['la compuerta evalúa una condición (ej. descuento > 15% o pedido > $5,000)', 'en SAP B1 se parametriza como Modelo de Autorización con etapas y autores', 'bloquea el documento hasta que el usuario autorizado apruebe la solicitud'] },
    { question: '¿Qué relación existe entre los Lanes de un diagrama BPMN y la definición de Usuarios y Autorizaciones en el ERP?', rubric: ['cada Lane representa un rol operativo o departamento (ej. Bodega, Compras, Finanzas)', 'en SAP B1 se traduce en perfiles de usuario y grupos de autorización', 'garantiza la segregación de funciones (SoD) en la empresa'] },
  ],
  'mod-28': [
    { question: 'Explica las técnicas de elicitación de requerimientos y el valor de aplicar los "Cinco Porqués" en entrevistas de negocio.', rubric: ['entrevistas estructuradas, observación de campo y análisis de documentación existente', 'la técnica de los Cinco Porqués profundiza hasta la causa raíz del problema', 'evita confundir síntomas con necesidades reales de negocio'] },
    { question: '¿Cuál es la diferencia entre el Business Requirements Document (BRD) y el Business Blueprint (BBD)?', rubric: ['el BRD define el "qué": requerimientos de negocio desde la perspectiva del cliente', 'el BBD define el "cómo": diseño funcional y técnico de cómo responderá SAP B1', 'el BBD sirve de contrato técnico para la fase de configuración'] },
    { question: 'Describe cómo se redacta una Historia de Usuario ágil y sus Criterios de Aceptación usando sintaxis Gherkin.', rubric: ['formato: Como [rol], quiero [funcionalidad], para [beneficio de negocio]', 'criterios de aceptación con estructura: Dado [contexto], Cuando [evento], Entonces [resultado]', 'elimina ambigüedades y facilita las pruebas de aceptación'] },
    { question: '¿Qué es una Matriz de Trazabilidad de Requisitos (RTM) y cómo asegura que ningún requerimiento quede huérfano?', rubric: ['tabla que vincula cada requerimiento de negocio con el BBD, caso de prueba y objeto SAP', 'garantiza cobertura completa de punta a punta', 'facilita la gestión de cambios y el control de alcance del proyecto'] },
    { question: 'Cuando un requerimiento de negocio no existe nativamente en SAP B1, ¿qué pasos sigue un consultor para solucionarlo mediante UDFs?', rubric: ['diseño del campo en Herramientas de Personalización especificando nombre, tipo y longitud', 'definición de valores válidos o listas desplegables para forzar datos limpios', 'colocación en el formulario o panel lateral UDF para acceso del usuario'] },
  ],
  'mod-29': [
    { question: 'Explica el uso de la Matriz de Mendelow (Poder vs Interés) en la gestión de stakeholders de un proyecto SAP.', rubric: ['clasifica interesados en 4 cuadrantes: Gestionar de cerca, Mantener satisfechos, Mantener informados, Monitorear', 'permite diseñar estrategias de comunicación personalizadas', 'previene bloqueos políticos y falta de apoyo de la alta dirección'] },
    { question: '¿Cuál es el procedimiento formal para gestionar una Solicitud de Cambio (Change Request) y evitar el Scope Creep?', rubric: ['registro del requerimiento nuevo con justificación de negocio', 'análisis de impacto en tiempo, costo y recursos del proyecto', 'aprobación o rechazo formal por el Comité de Dirección antes de ejecutarlo'] },
    { question: 'Describe la estructura de un Guion de Pruebas UAT (User Acceptance Test Script) efectivo.', rubric: ['código de caso de prueba, proceso vinculado y rol ejecutor', 'precondiciones y datos de prueba necesarios', 'pasos detallados a ejecutar, resultado esperado y resultado obtenido (Aprobado/Fallido)'] },
    { question: '¿En qué consiste la estrategia Train the Trainer (Capacitación a Capacitadores) y cuáles son sus ventajas en la adopción del cambio?', rubric: ['formación intensiva a usuarios clave (Key Users) de cada departamento', 'los usuarios clave capacitan a los usuarios finales en su propio lenguaje', 'fomenta el sentido de pertenencia y asegura soporte interno post-arranque'] },
    { question: '¿Qué verificaciones contables y operativas son indispensables antes de la firma formal del Acta de Go-Live?', rubric: ['validación de balance inicial cuadrado al centavo y saldos de terceros confirmados', 'inventario inicial valorado y cuadrante con bodega física', 'aprobación formal de la UAT y firma del acta de aceptación por el cliente y el sponsor'] },
  ],
};
