// ═══════════════════════════════════════════════════════════════════
// REGISTRO DE ARQUETIPOS DE SIMULADOR PARA LOS MANUALES SAP B1
// Clasificación exacta: Teóricos (sin formulario) vs Prácticos (9 arquetipos)
// ═══════════════════════════════════════════════════════════════════

export type SimulatorArchetype =
  | "query"           // Generador de Consultas SQL (Query Generator)
  | "sales"           // Documentos de Ventas (OQUT / ORDR / OINV)
  | "procurement"     // Documentos de Compras (OPOR / OPDN / OPCH)
  | "item_master"     // Datos Maestros de Artículo (OITM)
  | "uom_setup"       // Definición de Grupos de Unidades de Medida (OUGP / UGP1)
  | "inventory_move"  // Movimientos y Traslados de Stock (OIGN / OIGE / OWTR)
  | "bin_locations"   // Ubicaciones de Almacén (OBIN)
  | "journal_entry"   // Asiento Contable Manual (OJDT)
  | "banking"         // Pagos Recibidos y Efectuados (ORCT / OVPM)
  | "production"      // Lista de Materiales y Órdenes de Fabricación (OITT / OWOR)
  | "mrp"             // Asistente de Planificación MRP
  | "pricing"         // Listas de Precios y Descuentos (OPLN)
  | "cockpit"         // Parametrizaciones Generales y Cockpit Fiori
  | "none";           // Módulo puramente conceptual / teórico

export interface ManualSimulatorConfig {
  requiresSimulator: boolean;
  archetype: SimulatorArchetype;
  title: string;
  moduleName: string;
  defaultTable?: string;
  scenarioGoal?: string;
  theoreticalSummary?: string;
}

export const MANUAL_SIMULATOR_MAP: Record<string, ManualSimulatorConfig> = {
  "10_Intro_11_Overview_IntroSAPB1_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Introducción a SAP Business One",
    moduleName: "Introducción a SAP Business One",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Introducción a SAP Business One. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Intro_12_Overview_GettingStarted_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones Generales & Cockpit - Primeros Pasos en SAP Business One",
    moduleName: "Gestión > Inicialización del Sistema",
    defaultTable: "OADM - Administración",
    scenarioGoal: "Configurar la plantilla de rol de usuario, almacén por defecto y activación de widgets Fiori.",
  },
  "10_Overview_13_MDDoc_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Documentos y Datos Maestros: Conceptos Generales",
    moduleName: "Introducción a SAP Business One",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Introducción a SAP Business One. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Impl_11_CustomTools_Queries_ES": {
    requiresSimulator: true,
    archetype: "query",
    title: "Generador de Consultas SQL - Consultas Personalizadas (Queries)",
    moduleName: "Herramientas > Consultas",
    defaultTable: "OCRD - Business Partners",
    scenarioGoal: "Estructurar consulta SQL seleccionando campos de la tabla OCRD/OINV y aplicando filtros WHERE.",
  },
  "10_Impl_12_CustomTools_Alerts_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Sistema de Alertas Automáticas",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Sistema de Alertas Automáticas.",
  },
  "10_Impl_13_CustomTools_ApprovalProcesses_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Procesos de Aprobación",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Procesos de Aprobación.",
  },
  "10_Impl_14_CustomTools_UserDefinedFields_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Campos Definidos por el Usuario (UDF)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Campos Definidos por el Usuario (UDF).",
  },
  "10_Impl_15_CustomTools_UserDefinedValues_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Valores Definidos por el Usuario (UDV)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Valores Definidos por el Usuario (UDV).",
  },
  "10_Impl_16_CustomTools_UserDefinedTables_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Tablas Definidas por el Usuario (UDT)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Tablas Definidas por el Usuario (UDT).",
  },
  "10_Impl_17_CustomTools_IntroAnalytics_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Introducción a SAP Analytics",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Introducción a SAP Analytics.",
  },
  "10_Impl_21_ImplTools_ImplementationMethodology_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Metodología de Implementación SAP",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Metodología de Implementación SAP.",
  },
  "10_Impl_22_ImplTools_ExpressWizard_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Asistente Express de Configuración",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Asistente Express de Configuración.",
  },
  "10_Impl_23_ImplTools_Key_Settings_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Configuraciones Clave del Sistema",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Configuraciones Clave del Sistema.",
  },
  "10_Impl_25_ImplTools_OpeningBalances": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Carga de Saldos Iniciales",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Carga de Saldos Iniciales.",
  },
  "10_Impl_26_ImplTools_QuickCopy": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Copia Rápida entre Compañías (Quick Copy)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Copia Rápida entre Compañías (Quick Copy).",
  },
  "10_Impl_31_ImportfromExcel": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Importación de Datos desde Excel",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Importación de Datos desde Excel.",
  },
  "10_Impl_31_SystemSetup_Users_Groups_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Configuración de Usuarios y Grupos",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Configuración de Usuarios y Grupos.",
  },
  "10_Impl_32_SystemSetup_GeneralAuthorizations_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Autorizaciones Generales del Sistema",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Autorizaciones Generales del Sistema.",
  },
  "10_Impl_32_Using_Data_Trans_Workbench": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Uso del Data Transfer Workbench (DTW)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Uso del Data Transfer Workbench (DTW).",
  },
  "10_Impl_33_Importing_Docs_using_DTW": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Importación de Documentos con DTW",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Importación de Documentos con DTW.",
  },
  "10_Impl_33_SystemSetup_DataOwnership_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Propiedad de los Datos (Data Ownership)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Propiedad de los Datos (Data Ownership).",
  },
  "10_Impl_34_SystemSetup_DocumentMasterDataNumbering_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Numeración de Documentos y Datos Maestros",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Numeración de Documentos y Datos Maestros.",
  },
  "10_Impl_35_SystemSetup_UIConfigurationTemplates_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Plantillas de Configuración de Interfaz (UI)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Plantillas de Configuración de Interfaz (UI).",
  },
  "10_Impl_36_SystemSetup_Print_layouts": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Diseños de Impresión (Print Layouts)",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Diseños de Impresión (Print Layouts).",
  },
  "10_Impl_39_SystemSetup_EmailPrefrences": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Preferencias de Correo Electrónico",
    moduleName: "Implementación y Configuración",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Preferencias de Correo Electrónico.",
  },
  "10_AccBasics_11_AccBasics_Financial_Basics_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Conceptos Financieros Básicos",
    moduleName: "Contabilidad Básica",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Contabilidad Básica. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_AccBasics_12_AccBasics_Automatic_Journal_Entries_ES": {
    requiresSimulator: true,
    archetype: "journal_entry",
    title: "Asiento Contable Manual - Asientos Contables Automáticos",
    moduleName: "Finanzas > Asiento",
    defaultTable: "OJDT - Cabecera Asiento / JDT1 - Líneas",
    scenarioGoal: "Registrar líneas contables en Debe y Haber verificando que la suma de saldos cuadre a cero.",
  },
  "10_BankProcess_11_Handling_Payments_ES": {
    requiresSimulator: true,
    archetype: "banking",
    title: "Gestión de Pagos y Cobros - Gestión de Pagos Recibidos y Emitidos",
    moduleName: "Gestión de Bancos > Pagos",
    defaultTable: "ORCT - Pagos Recibidos / OVPM - Pagos Efectuados",
    scenarioGoal: "Asignar medio de pago (Transferencia / Cheque) y conciliar facturas pendientes.",
  },
  "10_BankProcess_12_Payments_Payment Wizard_ES": {
    requiresSimulator: true,
    archetype: "banking",
    title: "Gestión de Pagos y Cobros - Asistente de Pagos (Payment Wizard)",
    moduleName: "Gestión de Bancos > Pagos",
    defaultTable: "ORCT - Pagos Recibidos / OVPM - Pagos Efectuados",
    scenarioGoal: "Asignar medio de pago (Transferencia / Cheque) y conciliar facturas pendientes.",
  },
  "10_BankProcess_21_BankReconcile_Overview_ES": {
    requiresSimulator: true,
    archetype: "banking",
    title: "Gestión de Pagos y Cobros - Reconciliación Bancaria",
    moduleName: "Gestión de Bancos > Pagos",
    defaultTable: "ORCT - Pagos Recibidos / OVPM - Pagos Efectuados",
    scenarioGoal: "Asignar medio de pago (Transferencia / Cheque) y conciliar facturas pendientes.",
  },
  "10_ControlReports_11_FinReports_FinReports_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Informes Financieros del Sistema",
    moduleName: "Informes Financieros y Control",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Informes Financieros y Control. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_ControlReports_21_CashReports_cashflow_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Informe de Flujo de Caja",
    moduleName: "Informes Financieros y Control",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Informes Financieros y Control. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_ControlReports_22_CashReports_Aging_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Antigüedad de Saldos (Aging Report)",
    moduleName: "Informes Financieros y Control",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Informes Financieros y Control. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_ControlReports_23_CashReports_Dunning": {
    requiresSimulator: false,
    archetype: "none",
    title: "Proceso de Reclamaciones (Dunning)",
    moduleName: "Informes Financieros y Control",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Informes Financieros y Control. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_CostandBudget_11_CostAcc_CostAcc_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Contabilidad de Costos",
    moduleName: "Costos y Presupuestos",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Costos y Presupuestos. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_CostandBudget_12_CostAcc_MultiDimensions_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Centros de Costo: Múltiples Dimensiones",
    moduleName: "Costos y Presupuestos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Centros de Costo: Múltiples Dimensiones.",
  },
  "10_CostandBudget_13_CostAcc_CostAdjustment": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Ajuste de Costos de Inventario",
    moduleName: "Costos y Presupuestos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Ajuste de Costos de Inventario.",
  },
  "10_CostandBudget_21_Budget_Budget": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Gestión de Presupuestos",
    moduleName: "Costos y Presupuestos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Gestión de Presupuestos.",
  },
  "10_FinProcess_11_PostJE_PostJE_ES": {
    requiresSimulator: true,
    archetype: "journal_entry",
    title: "Asiento Contable Manual - Registro de Asientos Contables",
    moduleName: "Finanzas > Asiento",
    defaultTable: "OJDT - Cabecera Asiento / JDT1 - Líneas",
    scenarioGoal: "Registrar líneas contables en Debe y Haber verificando que la suma de saldos cuadre a cero.",
  },
  "10_FinProcess_12_PostJE_template_ES": {
    requiresSimulator: true,
    archetype: "journal_entry",
    title: "Asiento Contable Manual - Plantillas de Asientos Recurrentes",
    moduleName: "Finanzas > Asiento",
    defaultTable: "OJDT - Cabecera Asiento / JDT1 - Líneas",
    scenarioGoal: "Registrar líneas contables en Debe y Haber verificando que la suma de saldos cuadre a cero.",
  },
  "10_FinProcess_13_PostJE_voucher_ES": {
    requiresSimulator: true,
    archetype: "journal_entry",
    title: "Asiento Contable Manual - Documentos Preliminares (Vouchers)",
    moduleName: "Finanzas > Asiento",
    defaultTable: "OJDT - Cabecera Asiento / JDT1 - Líneas",
    scenarioGoal: "Registrar líneas contables en Debe y Haber verificando que la suma de saldos cuadre a cero.",
  },
  "10_FinProcess_21_PostPeriods_PostPeriods_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Periodos Contables y Ejercicios",
    moduleName: "Procesos Financieros",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Procesos Financieros. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_FinProcess_22_PostPeriods_PeriodClose": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Cierre de Periodo Contable",
    moduleName: "Procesos Financieros",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Cierre de Periodo Contable.",
  },
  "10_FinProcess_31_InternalRecon_InternalRecon_ES": {
    requiresSimulator: true,
    archetype: "journal_entry",
    title: "Asiento Contable Manual - Reconciliación Interna de Cuentas",
    moduleName: "Finanzas > Asiento",
    defaultTable: "OJDT - Cabecera Asiento / JDT1 - Líneas",
    scenarioGoal: "Registrar líneas contables en Debe y Haber verificando que la suma de saldos cuadre a cero.",
  },
  "10_FinSetup_11_COA_COAConcepts_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Plan de Cuentas: Conceptos Fundamentales",
    moduleName: "Configuración Financiera",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Plan de Cuentas: Conceptos Fundamentales.",
  },
  "10_FinSetup_11_Currencies_Currencies_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Configuración de Monedas y Tipos de Cambio",
    moduleName: "Configuración Financiera",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Configuración Financiera. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_FinSetup_12_COA_ManageCOA": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Gestión del Plan de Cuentas",
    moduleName: "Configuración Financiera",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Gestión del Plan de Cuentas.",
  },
  "10_FinSetup_21_DefaultGLAcc_DefaultGLAccOveriew_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Cuentas de Mayor por Defecto: Visión General",
    moduleName: "Configuración Financiera",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Cuentas de Mayor por Defecto: Visión General.",
  },
  "10_FinSetup_22_DefaultGLAcc_Traditional": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Cuentas de Mayor por Defecto: Modo Tradicional",
    moduleName: "Configuración Financiera",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Cuentas de Mayor por Defecto: Modo Tradicional.",
  },
  "10_FinSetup_23_DefaultGLAcc_Advanced": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Cuentas de Mayor por Defecto: Modo Avanzado",
    moduleName: "Configuración Financiera",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Cuentas de Mayor por Defecto: Modo Avanzado.",
  },
  "10_FixedAsset_11_FixedAsset_Intro_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Activos Fijos: Introducción",
    moduleName: "Activos Fijos",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Activos Fijos. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_FixedAsset_12_FixedAsset_Intro_Virtual_Asset_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Activos Fijos Virtuales",
    moduleName: "Activos Fijos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Activos Fijos Virtuales.",
  },
  "10_FixedAsset_21_FixedAsset_InitSettings": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Activos Fijos: Configuración Inicial",
    moduleName: "Activos Fijos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Activos Fijos: Configuración Inicial.",
  },
  "10_FixedAsset_31_WorkingProcessFA_Activate_AssetMD": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Activos Fijos: Activación y Datos Maestros",
    moduleName: "Activos Fijos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Activos Fijos: Activación y Datos Maestros.",
  },
  "10_FixedAsset_32_WorkingProcessFA_Depreciation_Adjustments": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Activos Fijos: Depreciación y Ajustes",
    moduleName: "Activos Fijos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Activos Fijos: Depreciación y Ajustes.",
  },
  "10_FixedAsset_33_WorkingProcessFA_Retirement_Monitoring": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Activos Fijos: Bajas y Monitoreo",
    moduleName: "Activos Fijos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Activos Fijos: Bajas y Monitoreo.",
  },
  "10_ItemInv_11_Item_ItemMD_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Datos Maestros de Artículos",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_ItemInv_12_Item_ItemGrp_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Grupos de Artículos",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_ItemInv_21_UoM_Overview_ES": {
    requiresSimulator: true,
    archetype: "uom_setup",
    title: "Grupos de Unidades de Medida (OUGP) - Visión General",
    moduleName: "Gestión > Definición > Inventario > Grupos de unidades de medida",
    defaultTable: "OUGP / UGP1 - Grupos y Conversión",
    scenarioGoal: "Estructurar unidades de medida alternativas respecto a la unidad base de inventario.",
  },
  "10_ItemInv_31_WM_WH_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Gestión de Almacenes",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_ItemInv_32_WM_GM_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Movimientos de Mercancía",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_ItemInv_41_Valuation_ValMethods_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Métodos de Valoración de Inventario",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_ItemInv_51_SNBatch_SNBatch_ES": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Gestión de Series y Lotes",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_Item_22_UoM_Setup": {
    requiresSimulator: true,
    archetype: "uom_setup",
    title: "Grupos de Unidades de Medida (OUGP) - Configuración y Conversión",
    moduleName: "Gestión > Definición > Inventario > Grupos de unidades de medida",
    defaultTable: "OUGP / UGP1 - Grupos y Reglas de Conversión",
    scenarioGoal: "Definir la unidad base y configurar la matriz de conversión de rollos y bobinas a metros.",
  },
  "10_Item_23_UoM_Weight": {
    requiresSimulator: true,
    archetype: "uom_setup",
    title: "Grupos de Unidades de Medida - Conversión por Peso y Volumen",
    moduleName: "Gestión > Definición > Inventario > Grupos de unidades de medida",
    defaultTable: "OUGP / UGP1 - Pesos y Volúmenes",
    scenarioGoal: "Gestionar factores de conversión por peso bruto y neto en unidades alternativas.",
  },
  "10_Item_24_UoM_Packaging": {
    requiresSimulator: true,
    archetype: "uom_setup",
    title: "Grupos de Unidades de Medida - Definición de Tipos de Paquete",
    moduleName: "Gestión > Definición > Inventario > Grupos de unidades de medida",
    defaultTable: "OUGP / UGP1 - Empaquetado",
    scenarioGoal: "Asignar tipos de paquete predeterminados a cada unidad de medida del grupo.",
  },
  "10_Item_42_SNBatch_Valuation": {
    requiresSimulator: true,
    archetype: "item_master",
    title: "Datos Maestros de Artículo - Series y Lotes: Valoración",
    moduleName: "Inventario > Datos Maestros de Artículo",
    defaultTable: "OITM - Maestro de Artículos",
    scenarioGoal: "Gestionar propiedades del artículo, método de valoración de stock y grupos de unidad de medida.",
  },
  "10_Inven_13_WM_PhyInv": {
    requiresSimulator: true,
    archetype: "inventory_move",
    title: "Movimientos de Inventario - Inventario Físico: Conteo y Ajuste",
    moduleName: "Inventario > Operaciones de Stock",
    defaultTable: "OIGN / OIGE - Entradas / Salidas de Mercancías",
    scenarioGoal: "Realizar traspaso de stock entre almacenes y registrar recuento de inventario.",
  },
  "10_Inven_21_PNP_PNPSales": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Proceso de Picking y Packing: Ventas",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Inven_22_PNP_PNPProduction": {
    requiresSimulator: true,
    archetype: "inventory_move",
    title: "Movimientos de Inventario - Proceso de Picking y Packing: Producción",
    moduleName: "Inventario > Operaciones de Stock",
    defaultTable: "OIGN / OIGE - Entradas / Salidas de Mercancías",
    scenarioGoal: "Realizar traspaso de stock entre almacenes y registrar recuento de inventario.",
  },
  "10_Inven_23_PNP_PNPTTransfer": {
    requiresSimulator: true,
    archetype: "inventory_move",
    title: "Movimientos de Inventario - Proceso de Picking y Packing: Transferencias",
    moduleName: "Inventario > Operaciones de Stock",
    defaultTable: "OIGN / OIGE - Entradas / Salidas de Mercancías",
    scenarioGoal: "Realizar traspaso de stock entre almacenes y registrar recuento de inventario.",
  },
  "10_BinLoc_11_Overview_Overview_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Ubicaciones de Almacén: Visión General",
    moduleName: "Ubicaciones en Almacén (Bin Locations)",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Ubicaciones en Almacén (Bin Locations). No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_BinLoc_12_Setup_Setup": {
    requiresSimulator: true,
    archetype: "bin_locations",
    title: "Ubicaciones en Almacén (Bin Locations) - Ubicaciones de Almacén: Configuración",
    moduleName: "Inventario > Ubicaciones",
    defaultTable: "OBIN - Maestro de Ubicaciones",
    scenarioGoal: "Configurar código de ubicación estructurado por Subnivel (Pasillo-Estante-Nivel).",
  },
  "10_BinLoc_13_Process_Process": {
    requiresSimulator: true,
    archetype: "bin_locations",
    title: "Ubicaciones en Almacén (Bin Locations) - Ubicaciones de Almacén: Proceso Operativo",
    moduleName: "Inventario > Ubicaciones",
    defaultTable: "OBIN - Maestro de Ubicaciones",
    scenarioGoal: "Configurar código de ubicación estructurado por Subnivel (Pasillo-Estante-Nivel).",
  },
  "10_BinLoc_14_Process_Weight": {
    requiresSimulator: true,
    archetype: "bin_locations",
    title: "Ubicaciones en Almacén (Bin Locations) - Ubicaciones de Almacén: Gestión por Peso",
    moduleName: "Inventario > Ubicaciones",
    defaultTable: "OBIN - Maestro de Ubicaciones",
    scenarioGoal: "Configurar código de ubicación estructurado por Subnivel (Pasillo-Estante-Nivel).",
  },
  "10_BinLoc_15_Reporting_Reporting": {
    requiresSimulator: true,
    archetype: "bin_locations",
    title: "Ubicaciones en Almacén (Bin Locations) - Ubicaciones de Almacén: Informes",
    moduleName: "Inventario > Ubicaciones",
    defaultTable: "OBIN - Maestro de Ubicaciones",
    scenarioGoal: "Configurar código de ubicación estructurado por Subnivel (Pasillo-Estante-Nivel).",
  },
  "10_BinLoc_16_Serial_Serial": {
    requiresSimulator: true,
    archetype: "bin_locations",
    title: "Ubicaciones en Almacén (Bin Locations) - Ubicaciones de Almacén: Números de Serie",
    moduleName: "Inventario > Ubicaciones",
    defaultTable: "OBIN - Maestro de Ubicaciones",
    scenarioGoal: "Configurar código de ubicación estructurado por Subnivel (Pasillo-Estante-Nivel).",
  },
  "10_MRP_11_MRP_Process_ES": {
    requiresSimulator: true,
    archetype: "mrp",
    title: "Asistente de Planificación MRP - Planificación de Necesidades (MRP): Proceso",
    moduleName: "MRP > Asistente de Planificación",
    defaultTable: "MRP Wizard Scenarios",
    scenarioGoal: "Ejecutar asistente de necesidades calculando recomendaciones de compra y fabricación.",
  },
  "10_MRP_12_ConsumeForecast": {
    requiresSimulator: true,
    archetype: "mrp",
    title: "Asistente de Planificación MRP - Pronósticos de Consumo y Demanda",
    moduleName: "MRP > Asistente de Planificación",
    defaultTable: "MRP Wizard Scenarios",
    scenarioGoal: "Ejecutar asistente de necesidades calculando recomendaciones de compra y fabricación.",
  },
  "10_MRP_13_MRP_BOM": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - MRP y Listas de Materiales (BOM)",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Pricing_11_Concept_PrConcept_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Determinación de Precios: Conceptos",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Pricing_21_Pricelist_CreatePricelist_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Creación de Listas de Precios",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Pricing_22_Pricelist_UpdatePricelist_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Actualización de Listas de Precios",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Pricing_31_DiscSP_PerVolDisc_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Descuentos por Período y Volumen",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Pricing_32_DiscSP_DiscGrp_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Grupos de Descuento",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Pricing_33_DiscSP_SpPrBP_ES": {
    requiresSimulator: true,
    archetype: "pricing",
    title: "Listas de Precios y Descuentos - Precios Especiales para Socios de Negocio",
    moduleName: "Inventario > Listas de Precios",
    defaultTable: "OPLN - Listas de Precios / ITM1 - Precios de Artículos",
    scenarioGoal: "Definir precio base, factor de lista y reglas de descuento por cantidad.",
  },
  "10_Production_11_Overview_Overview_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Producción: Visión General",
    moduleName: "Producción",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Producción. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Production_21_Resources_Resources_ES": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Recursos de Producción",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_22_Resources_Capacity_ES": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Capacidad de Recursos",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_31_BOM_BOM_ES": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Lista de Materiales (BOM)",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_41_Process_BasicProductionProcess_ES": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Proceso Básico de Orden de Producción",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_42_Process_ByProductsandAdditional": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Subproductos y Costos Adicionales",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_42_Process_RoutingProductionProcess_ES": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Rutas de Producción (Routing)",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_51_Accounting_Accounting": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Contabilización de Órdenes de Producción",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_Production_52_Accounting_Cost": {
    requiresSimulator: true,
    archetype: "production",
    title: "Producción y Lista de Materiales - Análisis de Costos de Producción",
    moduleName: "Producción > Orden de Fabricación",
    defaultTable: "OWOR - Órdenes de Fabricación / OITT - BOM",
    scenarioGoal: "Definir lista de componentes y emitir orden de fabricación para producto terminado.",
  },
  "10_ProjectManage_11_ProjectManage": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Gestión de Proyectos",
    moduleName: "Gestión de Proyectos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Gestión de Proyectos.",
  },
  "10_ProjectManage_11_ProjectManage_Billing": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones de Sistema - Facturación de Proyectos",
    moduleName: "Gestión de Proyectos",
    defaultTable: "Parametrizaciones de Formulario",
    scenarioGoal: "Comprobar parámetros y opciones operativas para Facturación de Proyectos.",
  },
  "10_Purch_11_Process_Process_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Proceso de Compras: Visión General",
    moduleName: "Compras y Aprovisionamiento",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Compras y Aprovisionamiento. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Purch_12_Process_Items_ES": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Compras: Artículos y Documentos",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_13_Process_PurchaseReqQt": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Solicitudes de Compra y Cotizaciones",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_14_Process_Services": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Compras de Servicios",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_21_Issues_GRPO_ES": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Entrada de Mercancías (GRPO)",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_22_Issues_ReturnsCM_ES": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Devoluciones y Notas de Crédito (Compras)",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_32_LandedCost_Freight": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Costos de Importación: Fletes",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Purch_32_LandedCost_ManageLandedCosts": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Gestión de Costos de Importación (Landed Costs)",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "10_Sales_11_Process_Overview_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Proceso de Ventas: Visión General",
    moduleName: "Ventas",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Ventas. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Sales_12_Process_Order2Cash_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - De Pedido a Cobro (Order to Cash)",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Sales_21_Cust_Customers_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Datos Maestros de Clientes",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Sales_31_CRM_CRM_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Gestión de Relaciones con Clientes (CRM)",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Sales_41_Process_Autom_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Automatización del Proceso de Ventas",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Sales_51_Issues_ReturnsExchange_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Devoluciones y Cambios (Ventas)",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Sales_52_Issues_CM_ES": {
    requiresSimulator: true,
    archetype: "sales",
    title: "Documento de Ventas - Notas de Crédito (Ventas)",
    moduleName: "Ventas - Clientes",
    defaultTable: "ORDR / OINV - Factura de Clientes",
    scenarioGoal: "Registrar orden o factura para el cliente C20000 (Maxi-Teq) con cálculo automático de totales e IVA.",
  },
  "10_Service_11_CSProcess_Process_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Gestión de Llamadas de Servicio",
    moduleName: "Gestión de Servicios",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Gestión de Servicios. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "10_Support_11_SupportProcTool_ES": {
    requiresSimulator: false,
    archetype: "none",
    title: "Herramientas de Soporte y Diagnóstico",
    moduleName: "Herramientas de Soporte",
    theoreticalSummary: "Este manual aborda la arquitectura conceptual, normativas y modelos de negocio de Herramientas de Soporte. No requiere captura de datos transaccionales. Enfócate en el video explicativo y el Examen Oral con el Profesor IA.",
  },
  "CSI08_Query Practice_Solutions": {
    requiresSimulator: true,
    archetype: "query",
    title: "Generador de Consultas SQL - Práctica de Consultas SQL: Soluciones",
    moduleName: "Herramientas > Consultas",
    defaultTable: "OCRD - Business Partners",
    scenarioGoal: "Estructurar consulta SQL seleccionando campos de la tabla OCRD/OINV y aplicando filtros WHERE.",
  },
  "CSI08_Query_Practice": {
    requiresSimulator: true,
    archetype: "query",
    title: "Generador de Consultas SQL - Práctica de Consultas SQL",
    moduleName: "Herramientas > Consultas",
    defaultTable: "OCRD - Business Partners",
    scenarioGoal: "Estructurar consulta SQL seleccionando campos de la tabla OCRD/OINV y aplicando filtros WHERE.",
  },
  "CSL01_Introduction_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones Generales & Cockpit - Caso Práctico: Introducción",
    moduleName: "Gestión > Inicialización del Sistema",
    defaultTable: "OADM - Administración",
    scenarioGoal: "Configurar la plantilla de rol de usuario, almacén por defecto y activación de widgets Fiori.",
  },
  "CSL01_Introduction_Solution_ES": {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones Generales & Cockpit - Caso Práctico: Introducción (Solución)",
    moduleName: "Gestión > Inicialización del Sistema",
    defaultTable: "OADM - Administración",
    scenarioGoal: "Configurar la plantilla de rol de usuario, almacén por defecto y activación de widgets Fiori.",
  },
  "CSL02_Procurement_Process_ES": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Caso Práctico: Proceso de Aprovisionamiento",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
  "CSL02_Procurement_Process_Solution_ES": {
    requiresSimulator: true,
    archetype: "procurement",
    title: "Documento de Compras - Caso Práctico: Aprovisionamiento (Solución)",
    moduleName: "Compras - Proveedores",
    defaultTable: "OPOR / OPDN - Pedido y Entrada de Mercancías",
    scenarioGoal: "Emitir pedido de compras al proveedor S10000 (Far East Imports) y dar entrada de almacén.",
  },
};

export function getManualSimulatorConfig(manualId: string): ManualSimulatorConfig {
  if (MANUAL_SIMULATOR_MAP[manualId]) {
    return MANUAL_SIMULATOR_MAP[manualId];
  }
  // Fallback inteligente por coincidencia de texto
  const lower = manualId.toLowerCase();
  if (lower.includes("query") || lower.includes("csi08")) {
    return {
      requiresSimulator: true,
      archetype: "query",
      title: "Generador de Consultas SQL",
      moduleName: "Herramientas > Consultas",
      defaultTable: "OCRD - Business Partners",
      scenarioGoal: "Estructurar consulta SQL en la tabla OCRD con filtros y ordenamiento."
    };
  }
  if (lower.includes("purch") || lower.includes("csl02")) {
    return {
      requiresSimulator: true,
      archetype: "procurement",
      title: "Documentos de Compras",
      moduleName: "Compras - Proveedores",
      defaultTable: "OPOR - Pedido de Compras",
      scenarioGoal: "Emitir pedido de compras a proveedor y dar entrada de mercancías."
    };
  }
  if (lower.includes("sales")) {
    return {
      requiresSimulator: true,
      archetype: "sales",
      title: "Documentos de Ventas",
      moduleName: "Ventas - Clientes",
      defaultTable: "OINV - Factura de Clientes",
      scenarioGoal: "Crear factura de clientes con líneas de artículos y cálculo de totales."
    };
  }
  if (lower.includes("intro") || lower.includes("overview")) {
    return {
      requiresSimulator: false,
      archetype: "none",
      title: "Fundamentos Teóricos",
      moduleName: "Introducción y Arquitectura",
      theoreticalSummary: "Este manual aborda conceptos generales y arquitectura. No requiere formulario transaccional."
    };
  }
  return {
    requiresSimulator: true,
    archetype: "cockpit",
    title: "Parametrizaciones Generales",
    moduleName: "Gestión",
    defaultTable: "OADM - Parámetros",
    scenarioGoal: "Configurar opciones generales del sistema."
  };
}