/**
 * Equivalencia entre el id académico de cada manual ("1.1_Introduccion_a_SAP_Business_One") y su código
 * original ("10_Intro_11_Overview_IntroSAPB1_ES"), que es la clave de MANUAL_SPECIFIC_QUIZZES y MANUAL_SIMULATOR_MAP.
 *
 * Archivo generado a partir de manuals-120-data.ts (campo pdfPath). Existe para no importar ese archivo de 225 KB
 * en código que también usa el navegador (el simulador de Mi Aula lo cargaba en cada clase).
 * Regenerar si cambian los manuales: ver scripts/generar_codigos_manuales.mjs
 */
export const MANUAL_LEGACY_CODES: Record<string, string> = {
  "1.1_Introduccion_a_SAP_Business_One": "10_Intro_11_Overview_IntroSAPB1_ES",
  "1.2_Primeros_Pasos_en_SAP_Business_One": "10_Intro_12_Overview_GettingStarted_ES",
  "1.3_Documentos_y_Datos_Maestros_Concept": "10_Overview_13_MDDoc_ES",
  "22.1_Consultas_Personalizadas_Queries": "10_Impl_11_CustomTools_Queries_ES",
  "22.2_Sistema_de_Alertas_Automaticas": "10_Impl_12_CustomTools_Alerts_ES",
  "22.3_Procesos_de_Aprobacion": "10_Impl_13_CustomTools_ApprovalProcesses_ES",
  "22.4_Campos_Definidos_por_el_Usuario_UDF": "10_Impl_14_CustomTools_UserDefinedFields_ES",
  "22.5_Valores_Definidos_por_el_Usuario_UD": "10_Impl_15_CustomTools_UserDefinedValues_ES",
  "22.6_Tablas_Definidas_por_el_Usuario_UDT": "10_Impl_16_CustomTools_UserDefinedTables_ES",
  "22.7_Introduccion_a_SAP_Analytics": "10_Impl_17_CustomTools_IntroAnalytics_ES",
  "20.1_Metodologia_de_Implementacion_SAP": "10_Impl_21_ImplTools_ImplementationMethodology_ES",
  "20.2_Asistente_Express_de_Configuracion": "10_Impl_22_ImplTools_ExpressWizard_ES",
  "20.3_Configuraciones_Clave_del_Sistema": "10_Impl_23_ImplTools_Key_Settings_ES",
  "20.4_Carga_de_Saldos_Iniciales": "10_Impl_25_ImplTools_OpeningBalances",
  "20.5_Copia_Rapida_entre_Companias_Quick_": "10_Impl_26_ImplTools_QuickCopy",
  "20.6_Importacion_de_Datos_desde_Excel": "10_Impl_31_ImportfromExcel",
  "21.1_Configuracion_de_Usuarios_y_Grupos": "10_Impl_31_SystemSetup_Users_Groups_ES",
  "21.2_Autorizaciones_Generales_del_Sistem": "10_Impl_32_SystemSetup_GeneralAuthorizations_ES",
  "20.7_Uso_del_Data_Transfer_Workbench_DTW": "10_Impl_32_Using_Data_Trans_Workbench",
  "20.8_Importacion_de_Documentos_con_DTW": "10_Impl_33_Importing_Docs_using_DTW",
  "21.3_Propiedad_de_los_Datos_Data_Ownersh": "10_Impl_33_SystemSetup_DataOwnership_ES",
  "21.4_Numeracion_de_Documentos_y_Datos_Ma": "10_Impl_34_SystemSetup_DocumentMasterDataNumbering_ES",
  "21.5_Plantillas_de_Configuracion_de_Inte": "10_Impl_35_SystemSetup_UIConfigurationTemplates_ES",
  "21.6_Disenos_de_Impresion_Print_Layouts": "10_Impl_36_SystemSetup_Print_layouts",
  "21.7_Preferencias_de_Correo_Electronico": "10_Impl_39_SystemSetup_EmailPrefrences",
  "14.1_Conceptos_Financieros_Basicos": "10_AccBasics_11_AccBasics_Financial_Basics_ES",
  "14.2_Asientos_Contables_Automaticos": "10_AccBasics_12_AccBasics_Automatic_Journal_Entries_ES",
  "16.1_Gestion_de_Pagos_Recibidos_y_Emitid": "10_BankProcess_11_Handling_Payments_ES",
  "16.2_Asistente_de_Pagos_Payment_Wizard": "10_BankProcess_12_Payments_Payment Wizard_ES",
  "16.3_Reconciliacion_Bancaria": "10_BankProcess_21_BankReconcile_Overview_ES",
  "17.1_Informes_Financieros_del_Sistema": "10_ControlReports_11_FinReports_FinReports_ES",
  "17.2_Informe_de_Flujo_de_Caja": "10_ControlReports_21_CashReports_cashflow_ES",
  "17.3_Antiguedad_de_Saldos_Aging_Report": "10_ControlReports_22_CashReports_Aging_ES",
  "17.4_Proceso_de_Reclamaciones_Dunning": "10_ControlReports_23_CashReports_Dunning",
  "18.1_Contabilidad_de_Costos": "10_CostandBudget_11_CostAcc_CostAcc_ES",
  "18.2_Centros_de_Costo_Multiples_Dimensio": "10_CostandBudget_12_CostAcc_MultiDimensions_ES",
  "18.3_Ajuste_de_Costos_de_Inventario": "10_CostandBudget_13_CostAcc_CostAdjustment",
  "18.4_Gestion_de_Presupuestos": "10_CostandBudget_21_Budget_Budget",
  "15.1_Registro_de_Asientos_Contables": "10_FinProcess_11_PostJE_PostJE_ES",
  "15.2_Plantillas_de_Asientos_Recurrentes": "10_FinProcess_12_PostJE_template_ES",
  "15.3_Documentos_Preliminares_Vouchers": "10_FinProcess_13_PostJE_voucher_ES",
  "15.4_Periodos_Contables_y_Ejercicios": "10_FinProcess_21_PostPeriods_PostPeriods_ES",
  "15.5_Cierre_de_Periodo_Contable": "10_FinProcess_22_PostPeriods_PeriodClose",
  "15.6_Reconciliacion_Interna_de_Cuentas": "10_FinProcess_31_InternalRecon_InternalRecon_ES",
  "13.1_Plan_de_Cuentas_Conceptos_Fundament": "10_FinSetup_11_COA_COAConcepts_ES",
  "13.2_Configuracion_de_Monedas_y_Tipos_de": "10_FinSetup_11_Currencies_Currencies_ES",
  "13.3_Gestion_del_Plan_de_Cuentas": "10_FinSetup_12_COA_ManageCOA",
  "13.4_Cuentas_de_Mayor_por_Defecto_Vision": "10_FinSetup_21_DefaultGLAcc_DefaultGLAccOveriew_ES",
  "13.5_Cuentas_de_Mayor_por_Defecto_Modo_T": "10_FinSetup_22_DefaultGLAcc_Traditional",
  "13.6_Cuentas_de_Mayor_por_Defecto_Modo_A": "10_FinSetup_23_DefaultGLAcc_Advanced",
  "19.1_Activos_Fijos_Introduccion": "10_FixedAsset_11_FixedAsset_Intro_ES",
  "19.2_Activos_Fijos_Virtuales": "10_FixedAsset_12_FixedAsset_Intro_Virtual_Asset_ES",
  "19.3_Activos_Fijos_Configuracion_Inicial": "10_FixedAsset_21_FixedAsset_InitSettings",
  "19.4_Activos_Fijos_Activacion_y_Datos_Ma": "10_FixedAsset_31_WorkingProcessFA_Activate_AssetMD",
  "19.5_Activos_Fijos_Depreciacion_y_Ajuste": "10_FixedAsset_32_WorkingProcessFA_Depreciation_Adjustments",
  "19.6_Activos_Fijos_Bajas_y_Monitoreo": "10_FixedAsset_33_WorkingProcessFA_Retirement_Monitoring",
  "4.1_Datos_Maestros_de_Articulos": "10_ItemInv_11_Item_ItemMD_ES",
  "4.2_Grupos_de_Articulos": "10_ItemInv_12_Item_ItemGrp_ES",
  "4.3_Unidades_de_Medida_Vision_General": "10_ItemInv_21_UoM_Overview_ES",
  "5.1_Gestion_de_Almacenes": "10_ItemInv_31_WM_WH_ES",
  "5.2_Movimientos_de_Mercancia": "10_ItemInv_32_WM_GM_ES",
  "4.7_Metodos_de_Valoracion_de_Inventario": "10_ItemInv_41_Valuation_ValMethods_ES",
  "5.3_Gestion_de_Series_y_Lotes": "10_ItemInv_51_SNBatch_SNBatch_ES",
  "4.4_Unidades_de_Medida_Configuracion": "10_Item_22_UoM_Setup",
  "4.5_Unidades_de_Medida_Gestion_por_Peso": "10_Item_23_UoM_Weight",
  "4.6_Unidades_de_Medida_Empaquetado": "10_Item_24_UoM_Packaging",
  "5.4_Series_y_Lotes_Valoracion": "10_Item_42_SNBatch_Valuation",
  "5.5_Inventario_Fisico_Conteo_y_Ajuste": "10_Inven_13_WM_PhyInv",
  "5.6_Proceso_de_Picking_y_Packing_Ventas": "10_Inven_21_PNP_PNPSales",
  "6.1_Proceso_de_Picking_y_Packing_Produc": "10_Inven_22_PNP_PNPProduction",
  "6.2_Proceso_de_Picking_y_Packing_Transf": "10_Inven_23_PNP_PNPTTransfer",
  "7.1_Ubicaciones_de_Almacen_Vision_Gener": "10_BinLoc_11_Overview_Overview_ES",
  "7.2_Ubicaciones_de_Almacen_Configuracio": "10_BinLoc_12_Setup_Setup",
  "7.3_Ubicaciones_de_Almacen_Proceso_Oper": "10_BinLoc_13_Process_Process",
  "7.4_Ubicaciones_de_Almacen_Gestion_por_": "10_BinLoc_14_Process_Weight",
  "7.5_Ubicaciones_de_Almacen_Informes": "10_BinLoc_15_Reporting_Reporting",
  "7.6_Ubicaciones_de_Almacen_Numeros_de_S": "10_BinLoc_16_Serial_Serial",
  "9.1_Planificacion_de_Necesidades_MRP_Pr": "10_MRP_11_MRP_Process_ES",
  "9.2_Pronosticos_de_Consumo_y_Demanda": "10_MRP_12_ConsumeForecast",
  "9.3_MRP_y_Listas_de_Materiales_BOM": "10_MRP_13_MRP_BOM",
  "8.1_Determinacion_de_Precios_Conceptos": "10_Pricing_11_Concept_PrConcept_ES",
  "8.2_Creacion_de_Listas_de_Precios": "10_Pricing_21_Pricelist_CreatePricelist_ES",
  "8.3_Actualizacion_de_Listas_de_Precios": "10_Pricing_22_Pricelist_UpdatePricelist_ES",
  "8.4_Descuentos_por_Periodo_y_Volumen": "10_Pricing_31_DiscSP_PerVolDisc_ES",
  "8.5_Grupos_de_Descuento": "10_Pricing_32_DiscSP_DiscGrp_ES",
  "8.6_Precios_Especiales_para_Socios_de_N": "10_Pricing_33_DiscSP_SpPrBP_ES",
  "10.1_Produccion_Vision_General": "10_Production_11_Overview_Overview_ES",
  "10.2_Recursos_de_Produccion": "10_Production_21_Resources_Resources_ES",
  "10.3_Capacidad_de_Recursos": "10_Production_22_Resources_Capacity_ES",
  "10.4_Lista_de_Materiales_BOM": "10_Production_31_BOM_BOM_ES",
  "10.5_Proceso_Basico_de_Orden_de_Producci": "10_Production_41_Process_BasicProductionProcess_ES",
  "10.6_Subproductos_y_Costos_Adicionales": "10_Production_42_Process_ByProductsandAdditional",
  "10.7_Rutas_de_Produccion_Routing": "10_Production_42_Process_RoutingProductionProcess_ES",
  "10.8_Contabilizacion_de_Ordenes_de_Produ": "10_Production_51_Accounting_Accounting",
  "10.9_Analisis_de_Costos_de_Produccion": "10_Production_52_Accounting_Cost",
  "11.1_Gestion_de_Proyectos": "10_ProjectManage_11_ProjectManage",
  "11.2_Facturacion_de_Proyectos": "10_ProjectManage_11_ProjectManage_Billing",
  "3.1_Proceso_de_Compras_Vision_General": "10_Purch_11_Process_Process_ES",
  "3.2_Compras_Articulos_y_Documentos": "10_Purch_12_Process_Items_ES",
  "3.3_Solicitudes_de_Compra_y_Cotizacione": "10_Purch_13_Process_PurchaseReqQt",
  "3.4_Compras_de_Servicios": "10_Purch_14_Process_Services",
  "3.5_Entrada_de_Mercancias_GRPO": "10_Purch_21_Issues_GRPO_ES",
  "3.6_Devoluciones_y_Notas_de_Credito_Com": "10_Purch_22_Issues_ReturnsCM_ES",
  "3.7_Costos_de_Importacion_Fletes": "10_Purch_32_LandedCost_Freight",
  "3.8_Gestion_de_Costos_de_Importacion_La": "10_Purch_32_LandedCost_ManageLandedCosts",
  "2.1_Proceso_de_Ventas_Vision_General": "10_Sales_11_Process_Overview_ES",
  "2.2_De_Pedido_a_Cobro_Order_to_Cash": "10_Sales_12_Process_Order2Cash_ES",
  "2.3_Datos_Maestros_de_Clientes": "10_Sales_21_Cust_Customers_ES",
  "2.4_Gestion_de_Relaciones_con_Clientes_": "10_Sales_31_CRM_CRM_ES",
  "2.5_Automatizacion_del_Proceso_de_Venta": "10_Sales_41_Process_Autom_ES",
  "2.6_Devoluciones_y_Cambios_Ventas": "10_Sales_51_Issues_ReturnsExchange_ES",
  "2.7_Notas_de_Credito_Ventas": "10_Sales_52_Issues_CM_ES",
  "12.1_Gestion_de_Llamadas_de_Servicio": "10_Service_11_CSProcess_Process_ES",
  "23.1_Herramientas_de_Soporte_y_Diagnosti": "10_Support_11_SupportProcTool_ES",
  "23.7_Practica_de_Consultas_SQL_Solucione": "CSI08_Query Practice_Solutions",
  "23.6_Practica_de_Consultas_SQL": "CSI08_Query_Practice",
  "23.2_Caso_Practico_Introduccion": "CSL01_Introduction_ES",
  "23.3_Caso_Practico_Introduccion_Solucion": "CSL01_Introduction_Solution_ES",
  "23.4_Caso_Practico_Proceso_de_Aprovision": "CSL02_Procurement_Process_ES",
  "23.5_Caso_Practico_Aprovisionamiento_Sol": "CSL02_Procurement_Process_Solution_ES",
};

/** Código original de un manual, o undefined si no tiene otro código. */
export function legacyManualCode(manualId: string): string | undefined {
  return MANUAL_LEGACY_CODES[manualId];
}
