'use client';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import { financialSummary, today, trialBalance, usd } from '@/lib/company-calculations';
import { Screen, Field, Table, inputClass, buttonClass } from './SAPControls';
export default function FinancialStatementsScreen() {
  const c = useCompany(); const [tab, setTab] = useState(0); const [from, setFrom] = useState(today().slice(0, 4) + '-01-01'); const [to, setTo] = useState(today());
  const rows = trialBalance(c.data.chartOfAccounts, c.data.journalEntries, from, to); const balance = financialSummary(rows, c.data.profile?.incomeTaxRate); const period = financialSummary(rows.map(r => ({ ...r, closing: r.debit - r.credit })), c.data.profile?.incomeTaxRate);
  const operatingRevenue = -rows.filter(r => r.accountCode === '4.01').reduce((sum, r) => sum + r.debit - r.credit, 0);
  const otherRevenue = -rows.filter(r => r.accountCode === '4.02').reduce((sum, r) => sum + r.debit - r.credit, 0);
  const group = (prefix: string) => rows.filter(r => r.accountCode.startsWith(prefix)).reduce((s, r) => s + r.closing, 0);
  return <Screen title="Estados financieros"><div className="flex gap-2">{['Balance General', 'Estado de Resultados', 'Balance de Comprobación'].map((label, i) => <button className={buttonClass} key={label} aria-pressed={tab === i} onClick={() => setTab(i)}>{label}</button>)}</div><div className="grid gap-2 sm:grid-cols-2"><Field label="Desde"><input type="date" className={inputClass} value={from} onChange={e => setFrom(e.target.value)} /></Field><Field label="Hasta"><input type="date" className={inputClass} value={to} onChange={e => setTo(e.target.value)} /></Field></div>{tab === 0 ? <><Table headers={['Concepto', 'USD']} rows={[[ 'Activo corriente', usd(group('1.1.')) ], ['Activo no corriente', usd(group('1.2.'))], ['TOTAL ACTIVO', usd(balance.assets)], ['Pasivo corriente', usd(-group('2.1.'))], ['Pasivo no corriente', usd(-group('2.2.'))], ['TOTAL PASIVO', usd(balance.liabilities)], ['Patrimonio registrado', usd(balance.equity)], ['Resultados acumulados sin cerrar', usd(balance.profit)], ['PASIVO + PATRIMONIO + RESULTADO', usd(balance.liabilities + balance.equity + balance.profit)]]} /><p className={balance.difference === 0 ? 'font-bold text-green-800' : 'font-bold text-red-800'}>{balance.difference === 0 ? 'Balance cuadrado' : 'Diferencia: ' + usd(balance.difference)}</p></> : tab === 1 ? <><Table headers={['Concepto', 'USD']} rows={[[ 'Ingresos operacionales', usd(operatingRevenue) ], ['Costo de ventas', usd(period.cost)], ['Utilidad bruta', usd(operatingRevenue - period.cost)], ['Gastos operacionales', usd(period.expenses)], ['Utilidad operacional', usd(operatingRevenue - period.cost - period.expenses)], ['Otros ingresos', usd(otherRevenue)], ['Utilidad antes de impuestos', usd(period.profit)], ['IR estimado ' + c.data.profile?.incomeTaxRate + '%', usd(period.tax)], ['UTILIDAD NETA ESTIMADA', usd(period.net)]]} /><p>IR académico estimado; no contabilizado automáticamente. El balance incluye el resultado contable antes de esta estimación.</p></> : <><Table headers={['Cuenta', 'Nombre', 'Saldo anterior', 'Débitos', 'Créditos', 'Saldo final']} rows={rows.map(r => [r.accountCode, r.name, usd(r.opening), usd(r.debit), usd(r.credit), usd(r.closing)])} /><p>Débitos: {usd(rows.reduce((s, r) => s + r.debit, 0))} · Créditos: {usd(rows.reduce((s, r) => s + r.credit, 0))}</p></>}</Screen>;
}
