'use client';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import { usd } from '@/lib/company-calculations';
import { Screen, Field, Table, inputClass, buttonClass, SaveButton } from './SAPControls';
export default function InventoryReportScreen() {
  const c = useCompany(); const [itemCode, setItem] = useState(''); const [warehouse, setWarehouse] = useState(''); const [mode, setMode] = useState('stock'); const [qty, setQty] = useState(0);
  const stocks = c.data.warehouseStock.filter(s => (!itemCode || s.itemCode === itemCode) && (!warehouse || s.warehouseCode === warehouse));
  const movements = c.data.stockMovements.filter(s => (!itemCode || s.itemCode === itemCode) && (!warehouse || s.warehouseCode === warehouse));
  const lows = c.data.items.filter(i => i.type === 'inventory' && (!itemCode || i.itemCode === itemCode)).map(i => ({ item: i, quantity: stocks.filter(s => s.itemCode === i.itemCode).reduce((sum, s) => sum + s.quantity - s.reserved, 0) })).filter(r => r.quantity < r.item.minStock);
  return <Screen title="Inventario, kardex y valorización"><div className="flex flex-wrap gap-2">{['stock', 'kardex', 'mínimos', 'valorización'].map(m => <button key={m} className={buttonClass} aria-pressed={mode === m} onClick={() => setMode(m)}>{m}</button>)}</div><div className="grid gap-3 sm:grid-cols-2"><Field label="Artículo"><select className={inputClass} value={itemCode} onChange={e => setItem(e.target.value)}><option value="">Todos</option>{c.data.items.map(i => <option key={i.id} value={i.itemCode}>{i.itemCode} · {i.name}</option>)}</select></Field><Field label="Almacén"><select className={inputClass} value={warehouse} onChange={e => setWarehouse(e.target.value)}><option value="">Todos</option>{c.data.profile?.warehouses.map(w => <option key={w.code} value={w.code}>{w.name}</option>)}</select></Field></div>{mode === 'kardex' ? <Table headers={['Fecha', 'Artículo', 'Almacén', 'Referencia', 'Entrada / salida', 'Costo', 'Valor', 'Saldo']} rows={movements.map(m => [m.date, m.itemCode, m.warehouseCode, m.reference, m.quantity, usd(m.unitCost), usd(m.value), m.balance])} /> : mode === 'mínimos' ? <Table headers={['Artículo', 'Disponible', 'Mínimo', 'Punto reorden']} rows={lows.map(r => [r.item.name, r.quantity, r.item.minStock, r.item.reorderPoint])} /> : <><Table headers={['Artículo', 'Almacén', 'Stock', 'Reservado', 'Disponible', 'Método', 'Costo unitario', 'Valor']} rows={stocks.map(s => [s.itemCode, s.warehouseCode, s.quantity, s.reserved, s.quantity - s.reserved, s.costingMethod, usd(s.averageCost), usd(s.value)])} /><strong>Total valorizado: {usd(stocks.reduce((sum, s) => sum + s.value, 0))}</strong>{mode === 'valorización' && <Table headers={['Artículo', 'Almacén', 'Fecha capa', 'Cantidad capa', 'Costo capa']} rows={stocks.flatMap(s => s.layers.map(l => [s.itemCode, s.warehouseCode, l.date, l.quantity, usd(l.cost)]))} />}</>}<details className="border border-[#999] p-2"><summary>Ajuste educativo de inventario</summary><form className="mt-2 flex gap-2" onSubmit={async e => { e.preventDefault(); const item = c.data.items.find(i => i.itemCode === itemCode); if (!item) return; try { await c.save({ action: 'stock', data: { itemCode, warehouseCode: warehouse, qty, costingMethod: item.costingMethod } }); setQty(0); } catch { /* Provider error. */ } }}><Field label="Cantidad (+ entrada / − salida)" required><input required type="number" step="any" className={inputClass} value={qty} onChange={e => setQty(Number(e.target.value))} /></Field><SaveButton disabled={!itemCode || !warehouse || qty === 0} label="Registrar ajuste y asiento" /></form></details></Screen>;
}
