'use client';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import type { CommandData } from '@/lib/company-commands';
import { today, usd } from '@/lib/company-calculations';
import { Screen, Field, Navigation, Table, SaveButton, inputClass, buttonClass } from './SAPControls';
export default function ProductionOrderForm() {
  const c = useCompany();
  const prodBoms = c.data.boms.filter(b => b.type === 'production');
  const boms = prodBoms.length > 0 ? prodBoms : [
    { id: 'fb-bom-1', bomCode: 'BOM-A00001', parentItemCode: 'A00001', type: 'production' as const, components: [{ itemCode: 'A00007', quantity: 1, unit: 'UND', cost: 80 }, { itemCode: 'A00008', quantity: 1, unit: 'UND', cost: 45 }] }
  ];
  const warehouses = c.data.profile?.warehouses?.length ? c.data.profile.warehouses : [{ code: '01', name: 'Bodega Central' }, { code: '02', name: 'Bodega Sucursal' }];
  const blank = (): CommandData<'production'> => ({ bomCode: boms[0]?.bomCode || 'BOM-A00001', quantity: 1, warehouseCode: warehouses[0]?.code || '01', date: today(), dueDate: today() }); const [data, setData] = useState(blank); const [index, setIndex] = useState(-1);
  const order = c.data.productionOrders[index]; const bom = (c.data.boms.length > 0 ? c.data.boms : boms).find(b => b.bomCode === data.bomCode); const components = order?.components ?? bom?.components ?? []; const reset = () => { setIndex(-1); setData(blank()); };
  const statuses = { planned: 'Planificada', released: 'Liberada', in_progress: 'En proceso', closed: 'Cerrada' };
  const next: Record<string, 'released' | 'in_progress' | 'closed'> = { planned: 'released', released: 'in_progress', in_progress: 'closed' };
  return <Screen title="Orden de producción"><Navigation count={c.data.productionOrders.length} index={index} onNew={reset} onSelect={i => { setIndex(i); setData(c.data.productionOrders[i]); }} /><p>{order ? `${order.orderNumber} · ${statuses[order.status]}` : 'Nueva orden planificada'}</p><form className="space-y-3" onSubmit={async e => { e.preventDefault(); try { await c.save({ action: 'production', data }); reset(); } catch { /* Provider error. */ } }}><fieldset disabled={c.saving || index >= 0} className="grid gap-2 sm:grid-cols-3"><Field label="Producto / BOM" required><select required className={inputClass} value={data.bomCode} onChange={e => setData(d => ({ ...d, bomCode: e.target.value }))}><option value="">Seleccionar</option>{boms.map(b => <option key={b.id} value={b.bomCode}>{b.parentItemCode} · {b.bomCode}</option>)}</select></Field><Field label="Cantidad a producir" required><input required min="0.000001" step="any" type="number" className={inputClass} value={data.quantity} onChange={e => setData(d => ({ ...d, quantity: Number(e.target.value) }))} /></Field><Field label="Almacén" required><select className={inputClass} value={data.warehouseCode} onChange={e => setData(d => ({ ...d, warehouseCode: e.target.value }))}>{warehouses.map(w => <option key={w.code} value={w.code}>{w.name}</option>)}</select></Field><Field label="Fecha" required><input required type="date" className={inputClass} value={data.date} onChange={e => setData(d => ({ ...d, date: e.target.value }))} /></Field><Field label="Vencimiento" required><input required type="date" className={inputClass} value={data.dueDate} onChange={e => setData(d => ({ ...d, dueDate: e.target.value }))} /></Field></fieldset><Table headers={['Componente', 'Cantidad requerida', 'UM', 'Costo estimado']} rows={components.map(l => [l.itemCode, l.quantity * data.quantity, l.unit, usd(l.quantity * l.cost * data.quantity)])} /><SaveButton disabled={index >= 0} />{order && order.status !== 'closed' && <button type="button" className={buttonClass + ' ml-2'} disabled={c.saving} onClick={async () => { try { await c.save({ action: 'productionStatus', data: { id: order.id, status: next[order.status] } }); } catch { /* Provider error. */ } }}>{statuses[next[order.status]]}</button>}</form>{order?.status === 'closed' && <p>Costo real: {usd(order.actualCost)} · Asiento {order.journalEntryId || 'Sin valor de inventario'}</p>}</Screen>;
}
