'use client';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import { salesTypes } from '@/lib/firestore-types';
import { documentLabels } from '@/lib/company-engine';
import { today, usd } from '@/lib/company-calculations';
import { Field, inputClass, Screen, Table } from './SAPControls';
export default function SalesReportScreen() {
  const c = useCompany(); const [from, setFrom] = useState(today().slice(0, 7) + '-01'); const [to, setTo] = useState(today()); const [type, setType] = useState(''); const [customer, setCustomer] = useState('');
  const docs = c.data.salesOrders.filter(d => d.date >= from && d.date <= to && (!type || d.docType === type) && (!customer || d.cardCode === customer));
  const invoices = docs.filter(d => ['invoice', 'credit_note'].includes(d.docType));
  const net = (doc: typeof docs[number]) => doc.subtotal * (doc.docType === 'credit_note' ? -1 : 1);
  const customers = new Map<string, number>(); invoices.forEach(d => customers.set(d.cardName, (customers.get(d.cardName) ?? 0) + net(d)));
  const top = [...customers].sort((a, b) => b[1] - a[1])[0];
  const weeks = new Map<string, number>(); invoices.forEach(d => { const date = new Date(d.date + 'T00:00:00Z'); date.setUTCDate(date.getUTCDate() - (date.getUTCDay() + 6) % 7); const week = date.toISOString().slice(0, 10); weeks.set(week, (weeks.get(week) ?? 0) + net(d)); });
  const bars = [...weeks].sort((a, b) => a[0].localeCompare(b[0])); const maximum = Math.max(1, ...bars.map(b => Math.abs(b[1])));
  return <Screen title="Análisis de ventas"><div className="grid gap-2 sm:grid-cols-4"><Field label="Desde"><input type="date" className={inputClass} value={from} onChange={e => setFrom(e.target.value)} /></Field><Field label="Hasta"><input type="date" className={inputClass} value={to} onChange={e => setTo(e.target.value)} /></Field><Field label="Tipo"><select className={inputClass} value={type} onChange={e => setType(e.target.value)}><option value="">Todos</option>{salesTypes.map(t => <option key={t} value={t}>{documentLabels[t]}</option>)}</select></Field><Field label="Cliente"><select className={inputClass} value={customer} onChange={e => setCustomer(e.target.value)}><option value="">Todos</option>{c.data.customers.map(p => <option key={p.id} value={p.cardCode}>{p.name}</option>)}</select></Field></div><div className="grid gap-2 sm:grid-cols-3">{[['Ventas netas del período (sin IVA)', usd(invoices.reduce((s, d) => s + net(d), 0))], ['Documentos', docs.length], ['Cliente principal', top ? top[0] : 'Sin ventas']].map(([label, value]) => <div key={label} className="border border-[#999] bg-white p-3"><p>{label}</p><strong className="text-lg">{value}</strong></div>)}</div><p>Facturas menos notas de crédito; las cotizaciones, pedidos y entregas no se suman como ventas.</p><svg role="img" aria-label="Ventas netas por semana; detalle disponible en la tabla" viewBox={`0 0 ${Math.max(600, bars.length * 100)} 250`} className="max-h-64 w-full bg-white"><line x1="0" y1="120" x2={Math.max(600, bars.length * 100)} y2="120" stroke="#999" />{bars.map(([week, value], i) => <g key={week}><rect x={i * 100 + 10} y={value >= 0 ? 120 - Math.abs(value) / maximum * 85 : 120} width="70" height={Math.abs(value) / maximum * 85} fill={value >= 0 ? '#0055A5' : '#990000'} /><text x={i * 100 + 10} y="224" fontSize="10">{week}</text><text x={i * 100 + 10} y="240" fontSize="10">{usd(value)}</text></g>)}</svg><Table headers={['Número', 'Fecha', 'Tipo', 'Cliente', 'Subtotal', 'IVA', 'Total']} rows={docs.map(d => [d.docNumber, d.date, documentLabels[d.docType], d.cardName, usd(d.subtotal), usd(d.tax), usd(d.total)]).concat([['TOTAL DOCUMENTOS (sin compensar tipos)', '', '', '', usd(docs.reduce((sum, d) => sum + d.subtotal, 0)), usd(docs.reduce((sum, d) => sum + d.tax, 0)), usd(docs.reduce((sum, d) => sum + d.total, 0))]])} /></Screen>;
}
