'use client';

import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { useCompany } from '@/hooks/useCompany';

export const inputClass = 'w-full min-w-16 border border-[#999] bg-white px-2 py-1 text-[11px] text-[#222] focus:bg-[#FFFDE7] focus:outline-2 focus:outline-[#0055A5] disabled:bg-[#ECE9D8]';
export const buttonClass = 'border border-[#999] bg-[#F5F4EE] px-3 py-1 text-[#222] hover:bg-[#FFFDE7] active:scale-95 disabled:cursor-not-allowed disabled:opacity-50 motion-reduce:transform-none';
export function Screen({ title, children }: { title: string; children: ReactNode }) { return <section className="flex h-full min-h-80 flex-col overflow-auto bg-[#ECE9D8] font-[Tahoma,Arial,sans-serif] text-[11px] text-[#222]"><h2 className="bg-gradient-to-r from-[#003366] to-[#0055A5] px-3 py-2 font-bold text-white">{title}</h2><div className="space-y-3 p-3">{children}</div></section>; }
export function Field({ label, required, children }: { label: string; required?: boolean; children: ReactNode }) { return <label className="block space-y-1"><span>{label} {required && <span className="text-red-700">*</span>}</span>{children}</label>; }
export function Busy() { return <span role="status" className="inline-flex items-center gap-2"><span aria-hidden="true" className="h-3 w-3 animate-spin rounded-full border-2 border-[#999] border-t-[#003366] motion-reduce:animate-none" />Procesando…</span>; }
export function SaveButton({ disabled, label = 'Añadir' }: { disabled?: boolean; label?: string }) { const c = useCompany(); return <button type="submit" disabled={disabled || c.saving || c.loading} className={buttonClass}>{c.saving ? <Busy /> : label}</button>; }
export function Navigation({ count, index, onSelect, onNew }: { count: number; index: number; onSelect: (index: number) => void; onNew: () => void }) {
  const c = useCompany();
  return <div className="flex flex-wrap items-center gap-2 bg-[#D4D0C8] p-2"><button type="button" aria-label="Documento anterior" disabled={c.saving || !count || index === 0} onClick={() => onSelect(index < 0 ? count - 1 : index - 1)} className={buttonClass}>◀</button><button type="button" aria-label="Documento siguiente" disabled={c.saving || !count || index >= count - 1} onClick={() => onSelect(index + 1)} className={buttonClass}>▶</button><button type="button" disabled={c.saving} onClick={onNew} className={buttonClass}>⊕ Nuevo</button><span>{index < 0 ? 'Nuevo documento' : `${index + 1} / ${count} · Consulta`}</span><button type="button" disabled={c.loading || c.saving} onClick={() => { void c.refresh(); }} className={buttonClass}>Actualizar</button></div>;
}
export function Table({ headers, rows }: { headers: string[]; rows: ReactNode[][] }) { return <div className="overflow-x-auto"><table className="w-full border-collapse bg-white text-left"><thead className="bg-[#D4D0C8]"><tr>{headers.map(h => <th key={h} scope="col" className="border border-[#999] p-2">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="hover:bg-[#FFFDE7]">{row.map((cell, j) => <td key={j} className="border border-[#999] p-2">{cell}</td>)}</tr>)}{!rows.length && <tr><td colSpan={headers.length} className="p-4 text-center">Sin registros. Crea el primer documento.</td></tr>}</tbody></table></div>; }
export function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null); const id = useId();
  useEffect(() => { const dialog = ref.current; dialog?.showModal(); return () => dialog?.close(); }, []);
  return <dialog ref={ref} onCancel={event => { event.preventDefault(); onClose(); }} aria-labelledby={id} className="max-h-[85dvh] w-[min(95vw,850px)] overflow-auto border border-[#999] bg-[#ECE9D8] p-4 font-[Tahoma,Arial,sans-serif] text-[11px] text-[#222] shadow-xl backdrop:bg-black/50"><div className="mb-3 flex items-center justify-between"><h2 id={id} className="font-bold">{title}</h2><button type="button" onClick={onClose} className={buttonClass}>Cerrar</button></div>{children}</dialog>;
}
export interface FieldDefinition<T> { key: keyof T; label: string; kind?: 'text' | 'number' | 'date' | 'email' | 'textarea' | 'checkbox' | 'select'; options?: { value: string; label: string }[]; required?: boolean; tab?: string; min?: number; max?: number }
export function MasterForm<T extends object>({ title, initial, records, fields, onSave }: { title: string; initial: T; records: (T & { id: string })[]; fields: FieldDefinition<T>[]; onSave: (value: T) => Promise<string> }) {
  const c = useCompany(); const [value, setValue] = useState<T>(initial); const [index, setIndex] = useState(-1); const [tab, setTab] = useState(fields[0]?.tab ?? 'General'); const tabs = [...new Set(fields.map(f => f.tab ?? 'General'))];
  const reset = () => { setValue(initial); setIndex(-1); };
  return <Screen title={title}><Navigation count={records.length} index={index} onNew={reset} onSelect={i => { setIndex(i); setValue(records[i]); }} /><p>{index >= 0 ? records[index]?.id : 'Código automático al guardar'}</p><div className="flex flex-wrap gap-1">{tabs.map(t => <button type="button" key={t} onClick={() => setTab(t)} aria-pressed={tab === t} className={`${buttonClass} ${tab === t ? 'font-bold' : ''}`}>{t}</button>)}</div><form onSubmit={async event => { event.preventDefault(); try { await onSave(value); reset(); } catch { /* Provider presents the error. */ } }} className="space-y-3"><fieldset disabled={c.saving || index >= 0} className="grid gap-3 sm:grid-cols-2">{fields.map(f => <div key={String(f.key)} hidden={(f.tab ?? 'General') !== tab}><Field label={f.label} required={f.required}>{f.kind === 'checkbox' ? <input type="checkbox" checked={Boolean(value[f.key])} onChange={e => setValue(v => ({ ...v, [f.key]: e.target.checked }))} /> : f.kind === 'select' ? <select className={inputClass} required={f.required} value={String(value[f.key])} onChange={e => setValue(v => ({ ...v, [f.key]: e.target.value }))}>{f.options?.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : f.kind === 'textarea' ? <textarea className={inputClass} value={String(value[f.key])} onChange={e => setValue(v => ({ ...v, [f.key]: e.target.value }))} /> : <input className={inputClass} type={f.kind ?? 'text'} required={f.required} min={f.min ?? (f.kind === 'number' ? 0 : undefined)} max={f.max} step={f.kind === 'number' ? 'any' : undefined} value={String(value[f.key])} onChange={e => setValue(v => ({ ...v, [f.key]: f.kind === 'number' ? Number(e.target.value) : e.target.value }))} />}</Field></div>)}</fieldset><SaveButton disabled={index >= 0} /><button type="button" disabled={c.saving} onClick={reset} className={`${buttonClass} ml-2`}>Cancelar</button></form></Screen>;
}
