'use client';
import { opcionRetencion } from '@/lib/sri-catalogo';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import { today, totals, usd } from '@/lib/company-calculations';
import { Screen, Table, Field, inputClass, buttonClass } from './SAPControls';
export default function TaxReportScreen() {
  const c = useCompany(); const [period, setPeriod] = useState(today().slice(0, 7)); const [tab, setTab] = useState('104');
  const sales = c.data.salesOrders.filter(d => d.date.startsWith(period) && ['invoice', 'credit_note'].includes(d.docType)); const purchases = c.data.purchaseOrders.filter(d => d.date.startsWith(period) && ['vendor_invoice', 'debit_note'].includes(d.docType));
  const taxSales = sales.reduce((s, d) => s + d.tax * (d.docType === 'credit_note' ? -1 : 1), 0); const taxPurchases = purchases.reduce((s, d) => s + d.tax, 0);
  const sri = c.data.sriDocuments.filter(d => d.date.startsWith(period) && d.status === 'AUTORIZADO');
  const iceSales = sales.reduce((s, d) => s + (d.ice ?? 0) * (d.docType === 'credit_note' ? -1 : 1), 0);
  const delPeriodo = (cuenta: string) => c.data.journalEntries.filter(e => e.date.startsWith(period)).flatMap(e => e.lines).filter(l => l.accountCode === cuenta).reduce((s, l) => s + l.debit - l.credit, 0);
  const retIVARecibidas = delPeriodo('1.1.11'); const retIRRecibidas = delPeriodo('1.1.10');
  const rolesDelPeriodo = c.data.payrollRuns.filter(r => r.period === period);
  const irEmpleados = rolesDelPeriodo.reduce((s, r) => s + r.lines.reduce((t, l) => t + (l.incomeTax ?? 0), 0), 0);
  const baseEmpleados = rolesDelPeriodo.reduce((s, r) => s + r.lines.filter(l => (l.incomeTax ?? 0) > 0).reduce((t, l) => t + l.contributory, 0), 0);
  const retentions = new Map<string, { base: number; value: number }>(); sri.filter(d => d.docType === '07' && d.status === 'AUTORIZADO').forEach(d => d.retentionLines.filter(l => l.tax === 'IR').forEach(l => { const clave = opcionRetencion(l.code)?.label ?? l.code; const row = retentions.get(clave) ?? { base: 0, value: 0 }; row.base += l.base; row.value += l.base * l.rate / 100; retentions.set(clave, row); }));
  return <Screen title="Reportes tributarios educativos"><p>Resumen académico; crédito tributario supuesto al 100% para compras registradas. No genera archivos aceptados por el SRI. Retenciones de renta que te practicaron tus clientes este mes (crédito para tu impuesto a la renta): {usd(retIRRecibidas)}.</p><Field label="Mes"><input type="month" className={inputClass} value={period} onChange={e => setPeriod(e.target.value)} /></Field><div className="flex gap-2">{['104', '103', 'ATS'].map(t => <button key={t} className={buttonClass} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === '104' ? <Table headers={['Concepto', 'USD']} rows={[...[15, 8, 5, 0].map(rate => ['Ventas base ' + rate + '%', usd(sales.reduce((s, d) => s + totals(d.lines.filter(l => l.taxRate === rate)).subtotal * (d.docType === 'credit_note' ? -1 : 1), 0))]), ['IVA cobrado', usd(taxSales)], ['ICE causado (va en su propio formulario)', usd(iceSales)], ['Compras base con crédito', usd(purchases.reduce((s, d) => s + totals(d.lines.filter(l => l.taxRate > 0)).subtotal, 0))], ['IVA pagado', usd(taxPurchases)], ['(−) Retenciones de IVA que te practicaron tus clientes', usd(retIVARecibidas)], ['A pagar / (a favor)', usd(taxSales - taxPurchases - retIVARecibidas)]]} /> : tab === '103' ? <Table headers={['Concepto (código SRI 2026)', 'Base imponible', 'Valor retenido']} rows={[...[...retentions].map(([code, row]) => [code, usd(row.base), usd(row.value)]), ...(irEmpleados > 0 ? [['302 · Relación de dependencia (retención de IR a empleados)', usd(baseEmpleados), usd(irEmpleados)]] : [])]} /> : <><Table headers={['Resumen mensual', 'Documentos', 'Subtotal', 'IVA']} rows={[[ 'Ventas', sales.length, usd(sales.reduce((s, d) => s + d.subtotal * (d.docType === 'credit_note' ? -1 : 1), 0)), usd(taxSales) ], ['Compras', purchases.length, usd(purchases.reduce((s, d) => s + d.subtotal, 0)), usd(taxPurchases)]]} /><p>Retenciones recibidas: {usd(sri.reduce((s, d) => s + d.ats.retencionesRecibidas, 0))}</p><Table headers={['Comprobante', 'Identificación', 'Sustento', 'Base gravada', 'IVA']} rows={sri.map(d => [d.number, d.ats.idProv, d.ats.sustentoTributario, usd(d.ats.baseImpGrav), usd(d.ats.montoIva)])} /></>}</Screen>;
}
