'use client';
import { useState } from 'react';
import { useCompany } from '@/hooks/useCompany';
import { today } from '@/lib/company-calculations';
import { Screen, Field, inputClass, buttonClass, SaveButton, Table, Navigation } from './SAPControls';
export default function WarehouseTransferForm() {
  const c = useCompany(); const [from, setFrom] = useState('PRINCIPAL'); const [to, setTo] = useState('SECUNDARIO'); const [date, setDate] = useState(today()); const [lines, setLines] = useState([{ itemCode: '', quantity: 1 }]); const [index, setIndex] = useState(-1);
  const ids = [...new Set(c.data.stockMovements.filter(m => m.reference.startsWith('TR-')).map(m => m.reference))];
  const reset = () => { setIndex(-1); setLines([{ itemCode: '', quantity: 1 }]); };
  return <Screen title="Transferencia entre almacenes"><Navigation count={ids.length} index={index} onNew={reset} onSelect={i => setIndex(i)} />{index >= 0 ? <Table headers={['Referencia', 'Artículo', 'Almacén', 'Cantidad', 'Fecha']} rows={c.data.stockMovements.filter(m => m.reference === ids[index]).map(m => [m.reference, m.itemCode, m.warehouseCode, m.quantity, m.date])} /> : <form className="space-y-3" onSubmit={async e => { e.preventDefault(); try { await c.save({ action: 'transfer', data: { from, to, date, lines } }); reset(); } catch { /* Provider error. */ } }}><fieldset disabled={c.saving} className="space-y-3"><div className="grid gap-2 sm:grid-cols-3">{[['Origen', from, setFrom], ['Destino', to, setTo]].map(([label, value, setter]) => <Field key={String(label)} label={String(label)} required><select className={inputClass} value={String(value)} onChange={e => { if (typeof setter === 'function') setter(e.target.value); }}>{c.data.profile?.warehouses.map(w => <option key={w.code} value={w.code}>{w.name}</option>)}</select></Field>)}<Field label="Fecha" required><input type="date" required className={inputClass} value={date} onChange={e => setDate(e.target.value)} /></Field></div>{lines.map((line, i) => <div key={i} className="flex gap-2"><select aria-label={'Artículo ' + (i + 1)} required className={inputClass} value={line.itemCode} onChange={e => setLines(ls => ls.map((l, j) => j === i ? { ...l, itemCode: e.target.value } : l))}><option value="">Artículo *</option>{c.data.items.filter(item => item.type === 'inventory').map(item => <option key={item.id} value={item.itemCode}>{item.name}</option>)}</select><input aria-label={'Cantidad ' + (i + 1)} required type="number" min="0.000001" step="any" className={inputClass} value={line.quantity} onChange={e => setLines(ls => ls.map((l, j) => j === i ? { ...l, quantity: Number(e.target.value) } : l))} /><button type="button" disabled={lines.length === 1} onClick={() => setLines(ls => ls.filter((_, j) => j !== i))} className={buttonClass}>✕</button></div>)}<button type="button" className={buttonClass} onClick={() => setLines(ls => [...ls, { itemCode: '', quantity: 1 }])}>+ Línea</button></fieldset><SaveButton disabled={from === to} label="Confirmar transferencia" /></form>}</Screen>;
}
